### ISSUE TITLE
New Install Issue - Table Creation

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_flowview#1]
I just installed the latest commit for this plugin against the latest dev commit for cacti. I believe I have setup the flow collector correctly and I am receiving flows and generating files. 

However I am not able to save Filter reports. From what I can tell the setup of the plugin did not create the table "plugin_flowview_queries". It looks like the rest of the flowview tables were created.

Is there a log I can reference to assist in determining why the queries table is not being built?

**Comment by smiles1969** [comment]
Appears its related to the name field with varchar 255, if I reduce the field max it creates the table. 

I was getting "index column size too large. the maximum column size is 767 bytes"

**Comment by cigamit** [comment]
there is nothing in that table definition that says more than 255 chars.  so, i'm not clear as to where you are going.

**Comment by smiles1969** [comment]
Since I am using the utf8mb4 character set, it uses 4 bytes per char instead of 3 (utf8). Since this table is using the name varchar 255 field for indexing, I cannot exceed 191 chars (191*4=764).

**Comment by cigamit** [comment]
oh, now that makes sense.  that column does not need an index anyway.  so, it was removed.  thanks for testing that.  are you working on any translations?

**Comment by smiles1969** [comment]
I am not working on any translations, I believe mb4 was a recommendation, not a requirement, when I set up this new dev box using  mysql 5.7 and a fresh install of cacti 1.0.0 dev branch.

Thanks!

Closing ticket.
