### ISSUE TITLE
Issue saving filters

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_flowview#10]
Hi there,

I haven't used this plugin before on any of its version so I'm not familiar on what it should do or not.

Are the "Report Parameters" suppose to be saved on Custom Filters? Because it sort of does it but it doesn't show it. So even if I change eg "Resolve addresses" to Yes and hit the SAVE button it sort of does it because the scheduled report sends the email without resolving addresses but if switch to a different filter and then switch back it shows the default parameters.

There is also an issue with the "Save" and "Save as" functions. I have to refresh the page to make it works, otherwise will do nothing.

One more question, is it possible to make the schedule reports attach the graphs?
![2017-07-11_11-22-59](https://user-images.githubusercontent.com/13456559/28044723-1ffb502c-662d-11e7-821c-68ed922a6612.gif)

Better explained in the attached gif.

Tested with FF 54.0.1(64 bit) and Chrome 59.0.3071.115 (Official Build) (64-bit)
Running Cacti 1.1.12

**Comment by cigamit** [comment]
I'll likely look at this over the weekend.

**Comment by cigamit** [comment]
This should be resolved now.
