### ISSUE TITLE
Change the name of config.php to something like config.php.template

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#100]
I suggest that we change the default config.php that is provided with Flowview to a more templated name (config.php.template or something).
So even if the user install it, he is forced to configur the config.php file.

I just screw up my config with an update on the develop branch, since my config.php was overwrited by the default config.php provided, and then all config I had on my external DB where not used and a news set was created on the dafault cacti DB.

**Comment by TheWitness** [comment]
Create a pull request renaming to config.php.dist.  with default where if the file is not present to use the Cacti DB.
