### ISSUE TITLE
Properly detect the Cacti base on Ubuntu and Debian

### ISSUE THREAD

**Issue by cheerfultime** [Cacti/plugin_flowview#106]
Hi,

flow-capture.service start failed

AlmaLinux release 9.4
flowview 3.3 develop from github 

2024-05-31 09:57:54 - ERROR PHP ERROR in  Plugin 'flowview': Uncaught Error: Call to undefined function flowview_connect() in /usr/share/cacti/plugins/flowview/service/flow-capture:75 Stack trace: #0 /usr/share/cacti/plugins/flowview/service/flow-capture(50): start() #1 {main} thrown in file: /usr/share/cacti/plugins/flowview/service/flow-capture on line: 75

Thanks!

**Comment by arno-st** [comment]
is you cacti_base set correctly inside flow_capture ?
`
$cacti_base = '/usr/share/cacti';
`

And can you try to add this line in position 38 inside flow_capture
`
include_once($cacti_base . '/plugins/flowview/database.php');
`

**Comment by cheerfultime** [comment]
> is you cacti_base set correctly inside flow_capture ? `$cacti_base = '/usr/share/cacti';`

Yes.
in flow-capture
$cacti_base = '/usr/share/cacti';
 
> And can you try to add this line in position 38 inside flow_capture `include_once($cacti_base . '/plugins/flowview/database.php');`

after added this
2024-05-31 14:55:41 - ERROR PHP ERROR in  Plugin 'flowview': Uncaught Error: Call to undefined function flowview_connect() in /usr/share/cacti/plugins/flowview/service/flow-capture:76 Stack trace: #0 /usr/share/cacti/plugins/flowview/service/flow-capture(51): start() #1 {main} thrown in file: /usr/share/cacti/plugins/flowview/service/flow-capture on line: 76

Thanks.

**Comment by arno-st** [comment]
Ok so it's not the missing line, you can remove it.

When did you take the develop code ?
It's should work 'as is'

**Comment by cheerfultime** [comment]
Installed On May 30.

**Comment by TheWitness** [comment]
Is this the latest develop?  In the latest develop, it checks for two differing paths.

**Comment by cheerfultime** [comment]
> Is this the latest develop? In the latest develop, it checks for two differing paths.

$cacti_base = '/usr/share/cacti';
if (!file_exists($cacti_base) || !is_dir($cacti_base)) {
        $cacti_base = '/usr/share/cacti';
}

**Comment by cheerfultime** [comment]
I try to use Ubuntu 22.04
flowview 3.3 latest develop from github on May 31

2024-06-01 08:51:40 - ERROR PHP ERROR in  Plugin 'flowview': Uncaught Error: Call to undefined function flowview_connect() in /var/www/html/cacti/plugins/flowview/service/flow-capture:75 Stack trace: #0 /var/www/html/cacti/plugins/flowview/service/flow-capture(50): start() #1 {main} thrown in file: /var/www/html/cacti/plugins/flowview/service/flow-capture on line: 75

**Comment by cheerfultime** [comment]
Does flow-capture store flow data directly into the database?
Or is it stored in a directory?

This error message occurs when I output the flow of Cisco Nexus7000 C7009 to cacti.

Thanks.

> I try to use Ubuntu 22.04 flowview 3.3 latest develop from github on May 31
> 
> 2024-06-01 08:51:40 - ERROR PHP ERROR in Plugin 'flowview': Uncaught Error: Call to undefined function flowview_connect() in /var/www/html/cacti/plugins/flowview/service/flow-capture:75 Stack trace: #0 /var/www/html/cacti/plugins/flowview/service/flow-capture(50): start() #1 {main} thrown in file: /var/www/html/cacti/plugins/flowview/service/flow-capture on line: 75

**Comment by TheWitness** [comment]
That's something that needs fixing.  Right now you have to stop the service, grab the latest update, re-enable the plugin, and restart the service. That should get it working again.

**Comment by TheWitness** [comment]
There have been a lot of updates as of late, we just need to finish off what remains before release.

**Comment by cheerfultime** [comment]
Hi,

Ubuntu 22.04
flowview 3.3 latest develop from github on Jun 4

I stopped the service, got the latest update, re-enabled the plugin, and restarted the service.

"systemctl start flow-capture" is ok
But this error message in cacti.log occurs when I output the flow of Cisco Nexus7000 C7009 to cacti.

2024-06-04 09:45:59 - ERROR PHP ERROR in  Plugin 'flowview': Uncaught Error: Call to undefined function flowview_connect() in /var/www/html/cacti/plugins/flowview/service/flow-capture:75 Stack trace: #0 /var/www/html/cacti/plugins/flowview/service/flow-capture(50): start() #1 {main} thrown in file: /var/www/html/cacti/plugins/flowview/service/flow-capture on line: 75
2024-06-04 09:45:59 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2024-06-04 09:45:59 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'flowview'

Thanks.

**Comment by cheerfultime** [comment]
AlmaLinux release 9.4
flowview 3.3 latest develop from github on Jun 4

I stopped the service, got the latest update, re-enabled the plugin, and restarted the service.

There is no outgoing traffic to cacti yet.
This error message occurs after "systemctl start flow-capture".

 Jun 04 10:57:07 cacti php[61388]: NOTE: Starting Flow Collection
 Jun 04 10:57:07 cacti php[61388]: PHP Fatal error:  Uncaught Error: Call to undefined function flowview_connect() in /usr/share/cacti/plugins/flowview/service/flow-c>
 Jun 04 10:57:07 cacti php[61388]: Stack trace:
 Jun 04 10:57:07 cacti php[61388]: #0 /usr/share/cacti/plugins/flowview/service/flow-capture(50): start()
 Jun 04 10:57:07 cacti php[61388]: #1 {main}
 Jun 04 10:57:07 cacti php[61388]:   thrown in /usr/share/cacti/plugins/flowview/service/flow-capture on line 75
 Jun 04 10:57:07 cacti systemd[1]: flow-capture.service: Control process exited, code=exited, status=255/EXCEPTION

Thanks.

**Comment by arno-st** [comment]
Why in your last 2 messages the path are not the same:
one time is :  /var/www/html/cacti/plugins/flowview/service/flow-capture

and the second time it's: /usr/share/cacti/plugins/flowview/service/flow-capture

That doesn't make sense !

So fixe the path, do a systemctl daemon-reload
and then retry it.

**Comment by cheerfultime** [comment]
Hi,

Ubuntu 22.04
Installed cacti by github, so the path is "/var/www/html/cacti"
And installed flowview by github.
In /var/www/html/cacti/plugins/flowview/service/flow-capture
"$cacti_base = '/var/www/html/cacti';"

AlmaLinux release 9.4
Installed cacti by "dnf install cacti", so the path is "/usr/share/cacti"
But installed flowview by github.
In /usr/share/cacti/plugins/flowview/service/flow-capture
$cacti_base = '/usr/share/cacti';

Thanks.

> Why in your last 2 messages the path are not the same: one time is : /var/www/html/cacti/plugins/flowview/service/flow-capture
> 
> and the second time it's: /usr/share/cacti/plugins/flowview/service/flow-capture
> 
> That doesn't make sense !
> 
> So fixe the path, do a systemctl daemon-reload and then retry it.

**Comment by arno-st** [comment]
ok
So you Alma version just doesn't start.
But your Ubuntu version start, but give the error when a flow is send from a Cisco 7000
That's correct ?

As for your question:
```
Does flow-capture store flow data directly into the database?
Or is it stored in a directory?
```

It's stored directly on the DB, depending of your config in config.php, inside the flowview directory.

**Comment by cheerfultime** [comment]
Yes, you are right.

Thanks.

> ok So you Alma version just doesn't start. But your Ubuntu version start, but give the error when a flow is send from a Cisco 7000 That's correct ?
> 
> As for your question:
> 
> ```
> Does flow-capture store flow data directly into the database?
> Or is it stored in a directory?
> ```
> 
> It's stored directly on the DB, depending of your config in config.php, inside the flowview directory.

**Comment by TheWitness** [comment]
I'll be fixing this `flowview_connect()` issue this morning.

**Comment by arno-st** [comment]
Oups, i've got this error now:
```
04/06/2024  15:17:56 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_devices.php[89]:show_devices(),  /plugins/flowview/flowview_devices.php[498]:flowview_db_fetch_assoc(),  /plugins/flowview/database.php[153]:db_fetch_assoc(),  /lib/database.php[707]:db_fetch_assoc_prepared(),  /lib/database.php[727]:db_execute_prepared())
--
04/06/2024 15:17:56 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'flow_test.plugin_flowview_device_streams' doesn't exist
```

Didn't have that before, did you change the name of the table plugin_flowview_device to plugin_flowview_device_streams ?

**Comment by arno-st** [comment]
Hmm I see why.
Is it a new table ?
I'ts created on setup.php, but only when the version number change, otherwise not.

**Comment by arno-st** [comment]
Changing the version inside the plugin_config to 3.2 to recreate the table give me this error:
``
04/06/2024 16:02:16 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'flowview'
--
04/06/2024 16:02:16 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
04/06/2024 16:02:16 - ERROR PHP ERROR in  Plugin 'flowview':  Uncaught Error: Call to undefined function flowview_db_index_exists() in  /usr/share/cacti/plugins/flowview/setup.php:146 Stack trace: #0  /usr/share/cacti/plugins/flowview/setup.php(67):  plugin_flowview_check_upgrade() #1  /usr/share/cacti/lib/plugins.php(825): plugin_flowview_check_config() #2  /usr/share/cacti/lib/plugins.php(835): api_plugin_check_config() #3  /usr/share/cacti/plugins.php(121): api_plugin_enable() #4 {main} thrown  in file: /usr/share/cacti/plugins/flowview/setup.php on line: 146
 ``

**Comment by TheWitness** [comment]
I think that @xmacan fixed a small bug in my table create logic.  Try extracting the CREATE TABLE logic from the setup.

**Comment by TheWitness** [comment]
Today's updates where pretty material.  We are getting close to release.  Then, we have a slew of new features that I've logged today.  I want to get some Template examples from various hardware platforms/vendors.

**Comment by arno-st** [comment]
Ok, so creating the missing table, let me start the flowview plugin.

As for the flowview_setup_table(), if it's call after the if ($current != $old) inside plugin_flowview_check_upgrade(), I think it will be fine.
Since the table are created only if missing
