### ISSUE TITLE
500 Internal Server Error Cacti 1.3-devel

### ISSUE THREAD

**Issue by thanhtranntkh** [Cacti/plugin_flowview#107]
I install plugin_flowview 3.3 for Cacti 1.3-devel (using Rocky OS 9.3). However the Listeners function (/cacti/plugins/flowview/flowview_devices.php) gets the following error 500 Internal Server Error.
I couldn't find this problem in the log so I couldn't find a solution to the error

**Comment by xmacan** [comment]
please use develop version. 3.3 is very old
https://github.com/Cacti/plugin_flowview/archive/refs/heads/develop.zip
