### ISSUE TITLE
Cacti shuts down Flowview due to memory limit?

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_flowview#11]
Hi there,

I'm running Cacti 1.1.12 and with only 1 listener so far. It's been running since early this morning and now it's been disabled.

> 2017/07/11 14:37:17 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'flowview'
> --
> 2017/07/11 14:37:17 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4430 cacti_debug_backtrace)
> 2017/07/11 14:37:17 - ERROR PHP ERROR in Plugin 'flowview': Allowed memory size of 268435456 bytes exhausted (tried to allocate 99 bytes) in file: /usr/share/cacti-1.1.12/plugins/flowview/functions.php on line: 739
> 

Current memory limit is set to 256M if this isn't enough could you recommend a value? I'm only running 1 listener so far but I'd like to have a least 6 on this installation.

One more thing, I know Flowview doesn't handle Scheduled reports once you've set them up, however while the plugin is disabled I keep getting the report sent to my email. I'd expect this to stop.

If you need further details, please let me know.

**Comment by cigamit** [comment]
I updated it to 512M.  Let me know if this clears things up.
