### ISSUE TITLE
Plugin Estatus - Not Compatible

### ISSUE THREAD

**Issue by ghost** [Cacti/plugin_flowview#12]
Hi everyone, 

I need to add this plugin to my cacti system but i can't figure out how to resolve this issue, i tried with Flowview version:  1.0-1 / 1.1-1 /2.0 (pulled from this site) and give 777 permission to plugin/ flowview directory. I read all of the issues, but still cannot find the solution.

![capture](https://user-images.githubusercontent.com/13982683/28927557-3bf6ad5a-7841-11e7-8f28-f3414e172f8b.JPG)

- CentOS Linux release 7.3.1611
- Cacti Version: 1.0.4
- RRDtool Version: RRDTool 1.4.x
- PHP Version: 5.4.16
- MariaDB: 10.1.22

Sorry for my bad english, im from Argentina ! 

Thanks for your help.

Regards

**Comment by cigamit** [comment]
Flowview 2.0 requires Cacti 1.1.1 or higher.

**Comment by ghost** [comment]
@cigamit, thanks for your reply !
