### ISSUE TITLE
Flowview 2.1 Not compatible

### ISSUE THREAD

**Issue by hgortega** [Cacti/plugin_flowview#13]
Hi, I am using cacti v 1.1.2 and I saw that flowview 2.1 is not compatible, where can I download Flowview 2.0 ? Thanks

**Comment by cigamit** [comment]
We have not implemented formal releases of the 1.x compatible plugins.  You will have to walk the Github back into the past and then download the version from that point in time.  I suggest you upgrade the Cacti instead.  We have addressed numerous bugs since the 1.1.2 release.
