### ISSUE TITLE
The CIDR syntax filtering does not return correct results

### ISSUE THREAD

**Issue by cheerfultime** [Cacti/plugin_flowview#132]
Hi,

AlmaLinux release 9.4 + cacti + flowview(3.4 latest develop from github on Jun 13)

1.
"Source IP" or "Dest IP" in "Protocol Filters" works for IP, but still not for range(x.x.x.x/24).
Is there anything I should pay attention to when entering "Source IP" or "Dest IP" range?
When fill range in "Source IP" or "Dest IP", there is no error messages in cacti.log.

2.
![Destination IP](https://github.com/Cacti/plugin_flowview/assets/55739637/dc046192-5b3a-41e6-a672-d40cfff0fa56)
When "Statistical Report" choose "Destination IP", the table has additional "Source DNS" and "Source IP" field.
Are those specially added fields?

![Source IP](https://github.com/Cacti/plugin_flowview/assets/55739637/751ec6e8-c557-4417-a438-1ede20f32d65)
When "Statistical Report" choose "Source IP", "Dest DNS" and "Dest IP" will not be displayed.

Thanks!

**Comment by TheWitness** [comment]
I found the code to do this within MySQL, just need to code it.  The code example is here:

https://stackoverflow.com/questions/595748/is-there-way-to-match-ip-with-ipcidr-straight-from-select-query

**Comment by TheWitness** [comment]
This is resolved now.
