### ISSUE TITLE
Use Arin to Find Unregistered Domains wont disable

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_flowview#136]
Need to dig abit more but even when Use Arin to Find Unregistered Domains is disabled in settings
flowview_get_owner_from_arin still gets called 

Settings table is updated as expected

**Comment by TheWitness** [comment]
This is due to the setting being cached once the flow_collector.php is started.  Maybe we need to send a hup to the service to tell it to reload this key setting.  What do you think?

**Comment by TheWitness** [comment]
Key settings, I guess the DNS IP's under Mail/Reporting/DNS would also be key....

![image](https://github.com/Cacti/plugin_flowview/assets/1439914/fe746ebf-7ef2-4762-b19e-c08c28874a22)

**Comment by bmfmancini** [comment]
Yeah either a hup
Or a shell  exec to systemd to restart the daemon

**Comment by TheWitness** [comment]
This should be resolved now under these two commits:

429e1072a80d040cead60e0c244afb2f1b6d406c
and
569e408a304a37336798412147987a4bfa4ddd8a
