### ISSUE TITLE
CMDPHP Column with field id 34 Does not exist for V4 flow template

### ISSUE THREAD

**Issue by Catalyst4948** [Cacti/plugin_flowview#137]
![CACTI](https://github.com/Cacti/plugin_flowview/assets/173124830/eaf9c1a0-216a-45a9-95e8-b238216b9206)

**Comment by Catalyst4948** [comment]
Good afternoon
I'm new to this and just starting to learn it.
I've been struggling with these errors for a couple of days and can't figure out what the problem is

**Comment by TheWitness** [comment]
Yea, no problem.  You entered our sandbox.  We are making heavy changes right now.  Since this one is duplicate, I close it and then if you could respond to my questions in the other, that would be good.
