### ISSUE TITLE
CMDPHP Column with field id 34 Does not exist for V4 flow template

### ISSUE THREAD

**Issue by Catalyst4948** [Cacti/plugin_flowview#138]
![CACTI](https://github.com/Cacti/plugin_flowview/assets/173124830/eaf9c1a0-216a-45a9-95e8-b238216b9206)

These kinds of errors still pop up quite often.

**Comment by TheWitness** [comment]
What hardware vendor and device type is this?  What is the streams flowview version (v9 or IPFIX)?  We have been making heavy changes to the plugin.  You might also want to consider downloading a fresh copy.

**Comment by Catalyst4948** [comment]
Cisco equipment model CISCO2911/K9 (revision 1.0)
I configured netflow v9 on it
![1](https://github.com/Cacti/plugin_flowview/assets/173124830/33fb9281-5278-4628-afe7-d30e92d7b26d)

**Comment by TheWitness** [comment]
Edit the listener, and then go to the Templates tab and take a screen grab and upload it.

**Comment by TheWitness** [comment]
I'll be committing a change shortly.  You might want to grab that and do an upgrade too.  I'll post here once it's done.

**Comment by Catalyst4948** [comment]
![3](https://github.com/Cacti/plugin_flowview/assets/173124830/d174f3f8-6128-4166-8416-32020f6f3923)

**Comment by Catalyst4948** [comment]
![2](https://github.com/Cacti/plugin_flowview/assets/173124830/a6195d64-dcd0-4fe6-9763-17a2879a152f)
The following error started appearing in the logs

**Comment by TheWitness** [comment]
I suspect you have a protocol filter in place.  Let me verify that this is working.

**Comment by Catalyst4948** [comment]
![4](https://github.com/Cacti/plugin_flowview/assets/173124830/230771a8-5dd2-4df5-a29f-b4265231885b)
Yes, I only indicated it in the filters TCP and UDP Protocols

**Comment by TheWitness** [comment]
Grab the latest copy and of the plugin and then let's see what other errors are going on.  Note that in Template 256, there is no Flow ID: 45, but there is for Template 258.

The reason that we are glad you are here is that we are trying to identify the minimal subset of Field ID's that constitute a full 'common' schema, and your Template 256 for that Cisco device tells us something new.

**Comment by Catalyst4948** [comment]
Sorry, I don’t quite understand what I need to do and how to select this Template

**Comment by TheWitness** [comment]
Download a fresh copy of the plugin, then:

```sh
php -q flowview_upgrade.php --forcever=3.3
systemctl restart flow-capture
```

**Comment by TheWitness** [comment]
The protocol errors should go away afterwards.  You may see some errors when you update the plugin, but they should be transient.

**Comment by Catalyst4948** [comment]
![6](https://github.com/Cacti/plugin_flowview/assets/173124830/a6d3badd-21be-4e0c-b396-3a1c78e34595)
I understand you were talking about these errors
when I made the transition to 3.3

**Comment by Catalyst4948** [comment]
![7](https://github.com/Cacti/plugin_flowview/assets/173124830/bce6b939-d631-450c-85b0-4b6bc0452c44)
somehow he began to behave strangely)

**Comment by TheWitness** [comment]
Take a fresh pull and those 'Column with field id' warnings should go away.

**Comment by Catalyst4948** [comment]
![8](https://github.com/Cacti/plugin_flowview/assets/173124830/2d035fc3-62a7-44a5-a1a6-53659f1bd030)
unfortunately it didn't give any results
the same errors keep popping up

**Comment by TheWitness** [comment]
Did you not update to the latest develop?  Field 34 is no long required.  You will have to restart flow-capture though...

**Comment by TheWitness** [comment]
Closing this one.  If you still get those errors (not the 34 but the other ones), open a new ticket.

**Comment by TheWitness** [comment]
Ope, I know what the other issue is now.  Stop using your own DNS and use local DNS for the moment.  I have to fix some buggy code there.  I'll open the ticket separately.

**Comment by TheWitness** [comment]
New bug here: https://github.com/Cacti/plugin_flowview/issues/141
