### ISSUE TITLE
cacti 1.1.21 install flowview 

### ISSUE THREAD

**Issue by Initarts** [Cacti/plugin_flowview#14]
After you install the plug-in, you start the plug-in, but no data is generated!
/opt/flowview/completed/router/2017-09-07
ls 
-rw-r--r-- 1 root   root    92 9月   7 22:57 ft-v05.2017-09-07.225617+0800
-rw-r--r-- 1 root   root    92 9月   7 22:58 ft-v05.2017-09-07.225701+0800
-rw-r--r-- 1 root   root    92 9月   7 22:59 ft-v05.2017-09-07.225801+0800
-rw-r--r-- 1 root   root    92 9月   7 23:00 ft-v05.2017-09-07.225901+0800
-rw-r--r-- 1 root   root    92 9月   7 23:01 ft-v05.2017-09-07.230001+0800
-rw-r--r-- 1 root   root    92 9月   7 23:02 ft-v05.2017-09-07.230101+0800
-rw-r--r-- 1 root   root    92 9月   7 23:03 ft-v05.2017-09-07.230201+0800
-rw-r--r-- 1 root   root    92 9月   7 23:04 ft-v05.2017-09-07.230301+0800
-rw-r--r-- 1 root   root    92 9月   7 23:05 ft-v05.2017-09-07.230401+0800
[root@lan-switch-cacti 2017-09-07]# cat ft-v05.2017-09-07.230801+0800|  flow-stat -f8
#  --- ---- ---- Report Information --- --- ---
#
# Fields:    Total
# Symbols:   Disabled
# Sorting:   None
# Name:      Destination IP
#
# Args:      flow-stat -f8 
#
#
# IPaddr         flows                 octets                packets
#

![image](https://user-images.githubusercontent.com/8800508/30170659-546b8606-9422-11e7-82f5-07acac323f18.png)
![image](https://user-images.githubusercontent.com/8800508/30170736-867ac530-9422-11e7-9c5e-fcba2d10a62e.png)

**Comment by cigamit** [comment]
Verify that your listener is actually configured to match the flow-capture script.  Ensure that you are using 'Cacti's flow-capture service and not the one that comes with flow-tools.  That is essential.  This way the directories should line up.  This is always the hardest part of setting up the listeners.
