### ISSUE TITLE
FlowView is not working

### ISSUE THREAD

**Issue by hgortega** [Cacti/plugin_flowview#15]
Hi, I have insalled FlowView on Centos 7 anda Cacti 1.1.19. I had installed Flow-capture, it is running and collecting data to directory (s). Linstener is configurated, but I cannot see the charts.

**Comment by cigamit** [comment]
Are you running Cacti's version of flow-capture service per the documentation?  Is the table view showing data.  If the table view is showing data, then you need to install flash or use chrome.

**Comment by hgortega** [comment]
Flow-capture version is  flow-tools 0.68.5.1-15.el7. I tried with Netflow version 1 and 5 in Cacti and device. No, the table view is not showing.
Also, I can see data in collected files with command flow-print

**Comment by cigamit** [comment]
You need to run our version of the flow-capture init script and not the one from flow-tools.  You did not confirm that.  Also, V5 works perfectly.

The flow-capture script in `/etc/init.d/` should begin with a shbang line `#!/usr/bin/php` and should have as like the 5th line `$no_http_headers = true;`, if that is not what you see, you need to read the README.md one more time.

**Comment by hgortega** [comment]
I am using the init script from flow-capture plugin
![init script](https://user-images.githubusercontent.com/31148266/30515825-c314d20a-9af4-11e7-8a1f-c183400b8a1f.jpg)

**Comment by cigamit** [comment]
Okay, well that's good

1) Post the output of the following command after restarting the service:

`ps -ef | grep flow-capture`

2) Also, for the listener that is not working, paste the 'Edit' page.

3) Finally, post an image of Console > Settings > Misc

**Comment by hgortega** [comment]
Attached are your request
1.   Post the output of the following command after restarting the service:
ps -ef | grep flow-capture
![ps](https://user-images.githubusercontent.com/31148266/30528181-1d2dbf66-9bf6-11e7-8f6e-4841446d364a.jpg)
2. Also, for the listener that is not working, paste the 'Edit' page
![listener](https://user-images.githubusercontent.com/31148266/30528246-bcbc0542-9bf6-11e7-993a-1d85899ffff6.jpg)
3. Finally, post an image of Console > Settings > Misc
![misc](https://user-images.githubusercontent.com/31148266/30528281-1100aa4a-9bf7-11e7-938f-6a607d655772.jpg)

**Comment by jpobeda** [comment]
Have you actually checked that your device is sending netflow to this collector?
Maybe running a tcpdump or something

What's on your /var/flow-tools/? do: ls -al /var/flow-tools/

**Comment by hgortega** [comment]
Yes, device is sending and server is receiving it.
I have files with data
![imagen](https://user-images.githubusercontent.com/31148266/32808242-5d35385e-c960-11e7-93bb-1fb543bf1b23.png)

**Comment by jpobeda** [comment]
So, in your config you've set "Directory" for that listener to be "nedetel" but when you do an ls -al I only see the flow files.

Cacti flowview will be looking at /var/flow-tools/nedetel for flows, does that directory exist?

**Comment by hgortega** [comment]
![imagen](https://user-images.githubusercontent.com/31148266/32813032-1495e7e0-c976-11e7-8871-f136d7312264.png)

**Comment by jpobeda** [comment]
Is Selinux enabled?

audit2allow -a

clog erros? apache errors? Might be file permission issues.

**Comment by hgortega** [comment]
Yes, Selinux is enabled. No errors

**Comment by jpobeda** [comment]
audit2allow -a

**Comment by hgortega** [comment]
![imagen](https://user-images.githubusercontent.com/31148266/32815985-a4fcf9aa-c984-11e7-9f9c-f75724b12b27.png)

**Comment by jpobeda** [comment]
Try audit2allow -a -M flowview

and then install it: semodule -i flowview.pp

Or if you don't want to do that, disable selinux for a couple of minutes and test it.

It's not a flowview bug/issue though, better handled on forums.

**Comment by hgortega** [comment]
I did it, but it doesn´t work

**Comment by netniV** [comment]
No further input, closing.

**Comment by netniV** [comment]
This may have been addressed with #22
