### ISSUE TITLE
flowview_dns_cache using wrong call to DB

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#151]
Latest dev repo.
```
28/06/2024  15:14:50 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_devices.php[108]:show_devices(),  /plugins/flowview/flowview_devices.php[676]:flowview_db_fetch_assoc(),  /plugins/flowview/database.php[153]:db_fetch_assoc(),  /lib/database.php[707]:db_fetch_assoc_prepared(),  /lib/database.php[727]:db_execute_prepared())
--
28/06/2024 15:14:50 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'version' in 'field list'
 ```

You call db_execute instead of flowview_db_execute

and check the source, I saw some other wrong call:
68:                             db_execute('DELETE FROM plugin_flowview_dnscache WHERE ' . array_to_sql_or($selected_items, 'id'));
87:                     $dns_list .= '<li>' . html_escape(db_fetch_cell_prepared('SELECT CONCAT(host, "(", ip, ")") AS name FROM plugin_flowview_dnscache WHERE id = ?', array($matches[1]))) . '</li>';
198:                                                            db_fetch_assoc('SELECT DISTINCT source
296:    $total_rows = db_fetch_cell("SELECT COUNT(*)
303:    $dns_cache = db_fetch_assoc("SELECT *

**Comment by TheWitness** [comment]
Yea, sorry about that.  I should likely setup a foreign database.

**Comment by TheWitness** [comment]
This should be resolved now.  Thanks for keeping me honest.
