### ISSUE TITLE
QA: Tables are not removed after deinstall

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_flowview#170]
After plugin deinstall I still have these tables in database:
+----------------------------------+
| Tables_in_cacti (%flow%)         |
+----------------------------------+
| plugin_flowview_irr_as_block     |
| plugin_flowview_irr_as_set       |
| plugin_flowview_irr_aut_num      |
| plugin_flowview_irr_domain       |
| plugin_flowview_irr_filter_set   |
| plugin_flowview_irr_inet_rtr     |
| plugin_flowview_irr_inetnum      |
| plugin_flowview_irr_irt          |
| plugin_flowview_irr_mntner       |
| plugin_flowview_irr_organisation |
| plugin_flowview_irr_peering_set  |
| plugin_flowview_irr_person       |
| plugin_flowview_irr_poem         |
| plugin_flowview_irr_poetic_form  |
| plugin_flowview_irr_role         |
| plugin_flowview_irr_route_set    |
| plugin_flowview_irr_rtr_set      |
+----------------------------------+

and 
| parallel_database_query             |
| parallel_database_query_map_1       |
| parallel_database_query_shard       |
| parallel_database_query_shard_cache

**Comment by TheWitness** [comment]
This should be resolved now.

**Comment by bmfmancini** [comment]
Confirmed this is good now closing this out
