### ISSUE TITLE
Provide Link in Cacti's Graph View to Flowview

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_flowview#179]
Use case - A firewall is monitored by cacti when the user views graph there could be an icon that can be clicked to a filter of traffic to and from the device 

Issues  I can think of is that of the firewall IP is a management IP and not the payload interface the filter would only show management traffic 

If  a DNS name is entered instead of an IP we would need to translate the DNS name to an IP for the filter

**Comment by TheWitness** [comment]
So, you mean the ex_addr right?

**Comment by bmfmancini** [comment]
Yes
