### ISSUE TITLE
Latest Dev release dosen't list flowview listener, but count them

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#183]
In the latest dev version, the view of the listener is empty, even if the system is able to count them:
![2024-07-29 15_07_54-Clipboard](https://github.com/user-attachments/assets/bc22bb1f-6bc8-4be5-b1b6-4b9c7b689acc)

And On the log I have:
`
29/07/2024  15:05:25 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[737]:update_stream_stats(),  /plugins/flowview/flow_collector.php[829]:flowview_db_execute_prepared(),  /plugins/flowview/database.php[85]:db_execute_prepared())
--
29/07/2024 15:05:25 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'version' in 'field list'
29/07/2024 15:05:25 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[737]:update_stream_stats(),  /plugins/flowview/flow_collector.php[829]:flowview_db_execute_prepared(),  /plugins/flowview/database.php[85]:db_execute_prepared())
29/07/2024 15:05:25 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'version' in 'field list'
29/07/2024 15:05:24 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[737]:update_stream_stats(),  /plugins/flowview/flow_collector.php[829]:flowview_db_execute_prepared(),  /plugins/flowview/database.php[85]:db_execute_prepared())
29/07/2024 15:05:24 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'version' in 'field list'
 `

**Comment by TheWitness** [comment]
Yea, this is due to the upgrade script bombing on you.  You can find the proper structure in setup.php.  In the mean time, adapt and manually do the alter.

**Comment by TheWitness** [comment]
The bigger concern is this missing Aria engine.  It's standard in MariaDB 10.3++, 10.5 is about to be EOL.  I'm running on 11.1.5 right now.

**Comment by arno-st** [comment]
Ok I will check that
And I'm running Server version: 10.6.17-MariaDB MariaDB Server

**Comment by TheWitness** [comment]
Yea, that is good enough I think.  It's just the upgrade script.  Did you happen to have a dump before you fixed it with the old table structure?

**Comment by TheWitness** [comment]
Should be fixed.  I'll bump the version once I get through these tickets.
