### ISSUE TITLE
Using maxscale for redundancy, flowview can't re-create a connection when primary server is down

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#185]
Hi,
In my setup I'm using Maxscale as agent on my cacti to have a redundancy on my DB server.
Cacti behave correctly and switch
But when the master is down, flowview is not re-creating a session on the new server, and it fill my log with:

`
31/07/2024  07:29:41 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[748]:process_fv9(),  /plugins/flowview/flow_collector.php[1334]:flowview_db_execute(),  /plugins/flowview/database.php[70]:db_execute(),  /lib/database.php[385]:db_execute_prepared())
--
31/07/2024 07:29:41 - CMDPHP ERROR: A DB Exec Failed!, Error: MySQL server has gone away
31/07/2024 07:29:41 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[748]:process_fv9(),  /plugins/flowview/flow_collector.php[1299]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1733]:flowview_get_dns_from_ip(),  /plugins/flowview/functions.php[5147]:flowview_db_execute_prepared(),  /plugins/flowview/database.php[85]:db_execute_prepared())
31/07/2024 07:29:41 - CMDPHP ERROR: A DB Exec Failed!, Error: MySQL server has gone away
31/07/2024 07:29:41 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[748]:process_fv9(),  /plugins/flowview/flow_collector.php[1299]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1733]:flowview_get_dns_from_ip(),  /plugins/flowview/functions.php[5076]:flowview_db_fetch_row_prepared(),  /plugins/flowview/database.php[151]:db_fetch_row_prepared(),  /lib/database.php[666]:db_execute_prepared())
31/07/2024 07:29:41 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31/07/2024 07:29:41 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[748]:process_fv9(),  /plugins/flowview/flow_collector.php[1299]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1730]:flowview_get_dns_from_ip(),  /plugins/flowview/functions.php[5347]:flowview_db_execute_prepared(),  /plugins/flowview/database.php[85]:db_execute_prepared())
31/07/2024 07:29:41 - CMDPHP ERROR: A DB Exec Failed!, Error: MySQL server has gone away
31/07/2024 07:29:41 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[748]:process_fv9(),  /plugins/flowview/flow_collector.php[1299]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1730]:flowview_get_dns_from_ip(),  /plugins/flowview/functions.php[5076]:flowview_db_fetch_row_prepared(),  /plugins/flowview/database.php[151]:db_fetch_row_prepared(),  /lib/database.php[666]:db_execute_prepared())
31/07/2024 07:29:41 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31/07/2024 07:29:41 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[748]:process_fv9(),  /plugins/flowview/flow_collector.php[1299]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1733]:flowview_get_dns_from_ip(),  /plugins/flowview/functions.php[5147]:flowview_db_execute_prepared(),  /plugins/flowview/database.php[85]:db_execute_prepared())
31/07/2024 07:29:41 - CMDPHP ERROR: A DB Exec Failed!, Error: MySQL server has gone away
31/07/2024 07:29:41 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[748]:process_fv9(),  /plugins/flowview/flow_collector.php[1299]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1733]:flowview_get_dns_from_ip(),  /plugins/flowview/functions.php[5076]:flowview_db_fetch_row_prepared(),  /plugins/flowview/database.php[151]:db_fetch_row_prepared(),  /lib/database.php[666]:db_execute_prepared())
31/07/2024 07:29:41 - CMDPHP ERROR: A DB Row Failed!, Error: MySQL server has gone away
31/07/2024 07:29:41 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[748]:process_fv9(),  /plugins/flowview/flow_collector.php[1299]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1730]:flowview_get_dns_from_ip(),  /plugins/flowview/functions.php[5147]:flowview_db_execute_prepared(),  /plugins/flowview/database.php[85]:db_execute_prepared())

`

My Maxscale configuration is the following:
[maxscale]
admin_audit_file=/DATA/maxscale/admin_audit.csv
admin_host=0.0.0.0
admin_secure_gui=false
log_notice=false
log_warn_super_user=true
threads=auto
logdir=/DATA/maxscale/

[lslmysp12]
type=server
address=10.0.24.16
port=3306
protocol=MariaDBBackend

[lslmysp11]
type=server
address=10.0.24.30
port=3306
protocol=MariaDBBackend

# Monitoring for the servers
[Galera_Monitor]
type=monitor
backend_connect_timeout=1000ms
backend_read_timeout=1000ms
backend_write_timeout=1000ms
module=galeramon
monitor_interval=500ms
password=<PASSWORD>
servers=lslmysp12,lslmysp11
user=<USER>

# Galera router service
[ServiceReadConn]
type=service
router_options=master
connection_keepalive=1000ms
max_connections=2048
password=<PASSWORD>
router=readconnroute
user=<USER>
targets=lslmysp12,lslmysp11

[ServiceReadWrite]
type=service
max_connections=2048
password=<PASSWORD>
router=readwritesplit
user=<USER>
targets=lslmysp11,lslmysp12
filters=Hint

[Hint]
type=filter
module=hintfilter

# Galera cluster listener
[Galera_Listener]
type=listener
service=ServiceReadConn
#service=ServiceReadWrite
protocol=MariaDBClient
port=6033

[Split_Listener]
type=listener
service=ServiceReadWrite
protocol=MariaDBClient
port=7033

**Comment by TheWitness** [comment]
Are you pointed to read/write split?

**Comment by TheWitness** [comment]
This is likely more about the setup than anything else.

**Comment by arno-st** [comment]
Well I do setup inside Cacti to use the read/write split, and on the config.inc I'm using the ServiceReadConn
Who suppose to switch to the second server.
Cacti is doing it.
I agree It can be a config error, but which one ?

**Comment by TheWitness** [comment]
Well, is it a separate database server, or a separate database on the Cacti server?

**Comment by TheWitness** [comment]
If it's a separate set of database servers, your connection should point to the ReadWrite split, and then you really don't need the maxscale integration as the second, third, ... servers will serve up the parallel connections leaving the main server to handle inserts and forwards.  If it's the main Cacti server, it's a bit more problematic as you can not rely really on the read write split from my experience as Cacti updates some tables just too quickly, at least the for the poller.

**Comment by arno-st** [comment]
My setup is:
2 DB servers (lslmysp11 and lslmysp12)
On those servers each plugin has it's own db: Cacti, syslog, flowview
And that's for the test and prod environment

The front of cacti prod and test are on 2 others servers.
All 4 servers use 2x 10Gb interfaces in LACP config.

Have to look for the setup of the server, but the 2 DB are old Oracle server, so pretty heavy machine ;)

**Comment by TheWitness** [comment]
There is an important setting for the ReadWriteSplit router that you must have in place.  It's this setting:

max_slave_connections=0

It has a special meaning that is super important for Cacti and that is that every connection needs to use the master server, whatever it happens to be.

This is another reason to have a separate router for the Flow View and Syslog plugins such that they can use all the servers in the cluster as opposed to only the primary master.

I suspect that it's possible to have multiple ReadWriteSplit routers in a single MaxScale.

So, I need to get that into the documentation though.

**Comment by TheWitness** [comment]
Going to close this now.  The updated maxscale.cnf should show you the way.
