### ISSUE TITLE
Console > Flowview > Databases give some error on sort fields

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#187]
latest Dev version of flowview.

When passing to all the tab of the databases view, I got a lot of error about the sort fields for the SQL query:

`
31/07/2024 11:56:58 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:58 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:58 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:58 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:58 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:58 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:57 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:57 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:57 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:56 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:56 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:56 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:56 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:56 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:56 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:55 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:55 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:55 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:54 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:54 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:54 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:54 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:54 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:54 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:53 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:53 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:53 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:53 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:53 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:52 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:52 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:52 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:51 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:51 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:51 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:51 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[840]:flowview_db_fetch_assoc_prepared(),  /plugins/flowview/database.php[182]:db_fetch_assoc_prepared(),  /lib/database.php[727]:db_execute_prepared())
31/07/2024 11:56:51 - CMDPHP ERROR: A DB Row Failed!, Error: FUNCTION flow_test.NATURAL_SORT_KEY does not exist
31/07/2024 11:56:51 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:51 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:51 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:49 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[840]:flowview_db_fetch_assoc_prepared(),  /plugins/flowview/database.php[182]:db_fetch_assoc_prepared(),  /lib/database.php[727]:db_execute_prepared())
31/07/2024 11:56:49 - CMDPHP ERROR: A DB Row Failed!, Error: FUNCTION flow_test.NATURAL_SORT_KEY does not exist
31/07/2024 11:56:49 - CMDPHP Filter Variable: sort_direction, Must have a default and none is set
31/07/2024 11:56:49 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:49 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
31/07/2024 11:56:45 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview_databases.php[54]:view_databases(),  /plugins/flowview/flowview_databases.php[196]:view_db_table(),  /plugins/flowview/flowview_databases.php[739]:CactiErrorHandler())
31/07/2024 11:56:45 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "sort" in file:  /usr/share/cacti/plugins/flowview/flowview_databases.php  on line: 739
 `

**Comment by TheWitness** [comment]
Should be resolved.
