### ISSUE TITLE
FlowView issues

### ISSUE THREAD

**Issue by lazarmihail** [Cacti/plugin_flowview#19]
Good day, 
I am having cacti 1.1.33 version and trying to test your flowview plugin but the flows are not showing. 
The way I did the setup 

1. Configure my router 

HOME(config)#do sh runn | i ip flow
ip flow-cache timeout active 5
 ip flow egress #on wan connection 
 ip flow ingress # on LAN connection 
ip flow-export source Vlan20
ip flow-export version 5
ip flow-export destination 192.168.2.50 2020

2. Configure the flow-tools on the ubuntu 16.04 server 

nms-server@ubuntu:~$ cat /etc/flow-tools/flow-capture.conf
#Home_Router
-w /var/netflow/flows/completed -n 275 -N 3 0/192.168.2.1/2020

3. restarted the flow-capture service 

4. Install the flowview plugin and set the path on the Misc tab section 
![screen shot 2018-01-23 at 15 39 49](https://user-images.githubusercontent.com/19284259/35278793-bfc28be6-0053-11e8-9b6f-c9d8b43d4a26.png)

5. Setting up the device under flow listener 

![screen shot 2018-01-23 at 15 41 21](https://user-images.githubusercontent.com/19284259/35278839-e59dc75e-0053-11e8-8228-9938472ea1db.png)

6. I am checking that the files are getting generated 

nms-server@ubuntu:/var/netflow/flows/completed/2018/2018-01/2018-01-23$ pwd
/var/netflow/flows/completed/2018/2018-01/2018-01-23

nms-server@ubuntu:/var/netflow/flows/completed/2018/2018-01/2018-01-23$ ls -lsh
total 176K
8.0K -rw-r--r-- 1 www-data www-data 7.9K Jan 23 04:52 ft-v05.2018-01-23.044924-0800
 16K -rw-r--r-- 1 www-data www-data  14K Jan 23 04:57 ft-v05.2018-01-23.045212-0800
 16K -rw-r--r-- 1 www-data www-data  15K Jan 23 05:02 ft-v05.2018-01-23.045725-0800
4.0K -rw-r--r-- 1 www-data www-data 1.9K Jan 23 05:02 ft-v05.2018-01-23.050209-0800
 12K -rw-r--r-- 1 www-data www-data 9.0K Jan 23 05:06 ft-v05.2018-01-23.050238-0800
4.0K -rw-r--r-- 1 www-data www-data 2.5K Jan 23 05:07 ft-v05.2018-01-23.050636-0800
8.0K -rw-r--r-- 1 www-data www-data 5.5K Jan 23 05:09 ft-v05.2018-01-23.050751-0800
 12K -rw-r--r-- 1 www-data www-data  11K Jan 23 05:13 ft-v05.2018-01-23.050930-0800
 16K -rw-r--r-- 1 www-data www-data  13K Jan 23 05:18 ft-v05.2018-01-23.051304-0800
 20K -rw-r--r-- 1 root     root      17K Jan 23 05:23 ft-v05.2018-01-23.051817-0800
 20K -rw-r--r-- 1 root     root      17K Jan 23 05:28 ft-v05.2018-01-23.052330-0800
 20K -rw-r--r-- 1 root     root      17K Jan 23 05:33 ft-v05.2018-01-23.052843-0800
 16K -rw-r--r-- 1 root     root      15K Jan 23 05:39 ft-v05.2018-01-23.053356-0800
4.0K -rw-r--r-- 1 root     root       84 Jan 23 05:39 tmp-v05.2018-01-23.053909-0800

7. When I am trying to see the flow, the output is blank, what I did wrong ? :)

Regards 
Mihail

**Comment by lazarmihail** [comment]
When I am checking the logs this is the output:

2018/01/25 09:12:58 - CMDPHP Validation Error, Variable:version, Value:8.8 Backtrace: (/plugins/flowview/flowview_devices.php: 182 save_devices)(/plugins/flowview/flowview_devices.php: 277 get_filter_request_var)(/lib/html_utility.php: 439 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)

The folder is called flowview under plugin folder but still is not creating any flow view files. 

Any ideas ?

If I am doing a tcpdump the flows are coming though 
nms-server@ubuntu:/usr/bin$ sudo tcpdump -u -v port 2020
tcpdump: listening on enp0s3, link-type EN10MB (Ethernet), capture size 262144 bytes
22:54:37.953600 IP (tos 0x0, ttl 255, id 8734, offset 0, flags [none], proto UDP (17), length 1492)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 1464
22:54:48.954288 IP (tos 0x0, ttl 255, id 8735, offset 0, flags [none], proto UDP (17), length 1492)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 1464
22:54:57.954832 IP (tos 0x0, ttl 255, id 8736, offset 0, flags [none], proto UDP (17), length 1492)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 1464
22:55:08.955518 IP (tos 0x0, ttl 255, id 8737, offset 0, flags [none], proto UDP (17), length 1396)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 1368
22:55:19.956156 IP (tos 0x0, ttl 255, id 8738, offset 0, flags [none], proto UDP (17), length 1492)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 1464
22:55:27.956733 IP (tos 0x0, ttl 255, id 8739, offset 0, flags [none], proto UDP (17), length 1492)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 1464
22:55:38.957408 IP (tos 0x0, ttl 255, id 8740, offset 0, flags [none], proto UDP (17), length 1444)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 1416
22:55:43.957660 IP (tos 0x0, ttl 255, id 8741, offset 0, flags [none], proto UDP (17), length 1492)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 1464
22:55:54.958343 IP (tos 0x0, ttl 255, id 8742, offset 0, flags [none], proto UDP (17), length 1492)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 1464
22:56:05.958931 IP (tos 0x0, ttl 255, id 8743, offset 0, flags [none], proto UDP (17), length 820)
    192.168.2.1.62614 > 192.168.2.50.2020: UDP, length 792

**Comment by cigamit** [comment]
1st, this page isn't for support requests, the Cacti forums are for that.

Anyway, 2 Questions:

1. Are using the provided flow-capture init.d script?
https://github.com/Cacti/plugin_flowview/blob/develop/flow-capture

2. Are both the server timezone and router timezone the same and are the clocks synced?

**Comment by lazarmihail** [comment]
Got it,

The time sync was the problem. Now is all working fine. 

Sorry for opening the ticket here.
