### ISSUE TITLE
Error when using IPFIX

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#194]
I try to use one of my device to send the traffic using IPFIX, and when The device send some data I got this error on cacti log:

05/08/2024  16:33:39 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flow_collector.php[812]:process_fv10(),  /plugins/flowview/flow_collector.php[1564]:CactiErrorHandler())
--
05/08/2024 16:33:39 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined variable $listener_id in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1564
05/08/2024 16:33:38 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flow_collector.php[812]:process_fv10(),  /plugins/flowview/flow_collector.php[1564]:CactiErrorHandler())
05/08/2024 16:33:38 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined variable $listener_id in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1564
05/08/2024 16:33:36 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flow_collector.php[812]:process_fv10(),  /plugins/flowview/flow_collector.php[1564]:CactiErrorHandler())
05/08/2024 16:33:36 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined variable $listener_id in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1564
05/08/2024 16:33:36 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flow_collector.php[812]:process_fv10(),  /plugins/flowview/flow_collector.php[1564]:CactiErrorHandler())
05/08/2024 16:33:36 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined variable $listener_id in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1564
05/08/2024 16:33:36 - FLOWVIEW Updating Listener:2 for ex_addr:10.1.128.10
 
Before it was setup to V9

**Comment by TheWitness** [comment]
Okay, this should be resolved now.
