### ISSUE TITLE
Undefined array key, since upgrade on the 7.08 arround 10:44 AM GMT

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#195]
I got this kind of error this morning, it come a few time, and the vanish, maybee it's due to the upgrade, but in this case it take 12h to happen after the upgrade!

08/08/2024  10:09:32 - CMDPHP The URL is  this:/cacti/plugins/flowview/flowview.php?action=view&query=10&timespan=session&ex_addr=10.35.1.35&device_id=&includeif=&sortfield=&cutofflines=&cutoffoctets=&printed=&statistics=&domains=false&graph_type=&graph_height=&table=false&bytes=false&packets=false&flows=false&predefined_timespan=0
--
08/08/2024 10:09:32 - CMDPHP PHP ERROR WARNING Backtrace:   (/graph_view.php[385]:grow_right_pane_tree(),  /lib/html_tree.php[1387]:html_graph_area(),  /lib/html.php[333]:graph_drilldown_icons(),  /lib/html.php[547]:api_plugin_hook(),  /lib/plugins.php[95]:api_plugin_run_plugin_hook(),  /lib/plugins.php[237]:flowview_graph_button(),  /plugins/flowview/setup.php[1238]:CactiErrorHandler())
08/08/2024 10:09:32 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "panel_flows" in file:  /usr/share/cacti/plugins/flowview/setup.php  on line: 1238
08/08/2024 10:09:32 - CMDPHP PHP ERROR WARNING Backtrace:   (/graph_view.php[385]:grow_right_pane_tree(),  /lib/html_tree.php[1387]:html_graph_area(),  /lib/html.php[333]:graph_drilldown_icons(),  /lib/html.php[547]:api_plugin_hook(),  /lib/plugins.php[95]:api_plugin_run_plugin_hook(),  /lib/plugins.php[237]:flowview_graph_button(),  /plugins/flowview/setup.php[1238]:CactiErrorHandler())
08/08/2024 10:09:32 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "panel_packets" in file:  /usr/share/cacti/plugins/flowview/setup.php  on line: 1238
08/08/2024 10:09:32 - CMDPHP PHP ERROR WARNING Backtrace:   (/graph_view.php[385]:grow_right_pane_tree(),  /lib/html_tree.php[1387]:html_graph_area(),  /lib/html.php[333]:graph_drilldown_icons(),  /lib/html.php[547]:api_plugin_hook(),  /lib/plugins.php[95]:api_plugin_run_plugin_hook(),  /lib/plugins.php[237]:flowview_graph_button(),  /plugins/flowview/setup.php[1238]:CactiErrorHandler())
08/08/2024 10:09:32 - ERROR PHP WARNING in  Plugin 'flowview':  Undefined array key "panel_bytes" in file:  /usr/share/cacti/plugins/flowview/setup.php  on line: 1238

**Comment by TheWitness** [comment]
Post a `desc` of the table plugin_flowview_queries

**Comment by TheWitness** [comment]
I did make one commit around this.  It's not going to fix your problem, but it reminded me that the Graph Zoom feature was not finished.  Thanks!

**Comment by arno-st** [comment]
here is the desc:
MariaDB [flow_test]> describe plugin_flowview_queries;
+-----------------+------------------+------+-----+---------+----------------+
| Field           | Type             | Null | Key | Default | Extra          |
+-----------------+------------------+------+-----+---------+----------------+
| id              | int(11) unsigned | NO   | PRI | NULL    | auto_increment |
| name            | varchar(255)     | NO   |     | NULL    |                |
| device_id       | int(11) unsigned | NO   |     | NULL    |                |
| template_id     | int(10)          | NO   |     | -1      |                |
| ex_addr         | varchar(46)      | NO   |     |         |                |
| timespan        | int(11) unsigned | NO   |     | 0       |                |
| startdate       | varchar(32)      | NO   |     | NULL    |                |
| enddate         | varchar(32)      | NO   |     | NULL    |                |
| tosfields       | varchar(32)      | NO   |     | NULL    |                |
| tcpflags        | varchar(32)      | NO   |     | NULL    |                |
| protocols       | varchar(32)      | YES  |     |         |                |
| sourceip        | varchar(255)     | NO   |     | NULL    |                |
| sourceport      | varchar(255)     | NO   |     | NULL    |                |
| sourceinterface | varchar(64)      | NO   |     | NULL    |                |
| sourceas        | varchar(64)      | NO   |     | NULL    |                |
| destip          | varchar(255)     | NO   |     | NULL    |                |
| destport        | varchar(255)     | NO   |     | NULL    |                |
| destinterface   | varchar(64)      | NO   |     | NULL    |                |
| destas          | varchar(64)      | NO   |     | NULL    |                |
| statistics      | int(3) unsigned  | NO   |     | NULL    |                |
| printed         | int(3) unsigned  | NO   |     | NULL    |                |
| includeif       | int(2) unsigned  | NO   |     | NULL    |                |
| sortfield       | varchar(15)      | YES  |     | bytes   |                |
| cutofflines     | varchar(8)       | NO   |     | NULL    |                |
| cutoffoctets    | varchar(8)       | NO   |     | NULL    |                |
| resolve         | varchar(2)       | NO   |     | NULL    |                |
| graph_type      | varchar(10)      | NO   |     | bar     |                |
| graph_height    | int(10) unsigned | NO   |     | 400     |                |
| panel_table     | char(2)          | NO   |     | on      |                |
| panel_bytes     | char(2)          | NO   |     | on      |                |
| panel_packets   | char(2)          | NO   |     | on      |                |
| panel_flows     | char(2)          | NO   |     | on      |                |
+-----------------+------------------+------+-----+---------+----------------+

**Comment by TheWitness** [comment]
You must have been viewing or something before the table schema was upgraded because those columns should always exist.

**Comment by TheWitness** [comment]
Try it again at your next opportunity and post your findings thank you.

**Comment by arno-st** [comment]
So I made an update this morning, and this problem is solve. But I got another one!!
New bug open!

**Comment by TheWitness** [comment]
Okay, I'll close this one then.
