### ISSUE TITLE
Flowview not displaying charts (Tables work)

### ISSUE THREAD

**Issue by jakkes72** [Cacti/plugin_flowview#21]
I installed Flowview on my Cactie hosts.
When applying a filter i see data, but no charts..

![afbeelding](https://user-images.githubusercontent.com/37660475/37770452-5ecdf6b2-2dcc-11e8-898e-60c8564657bc.png)

Even not with the "Bytes Bar" check mark applied

Because i see data, i think the netflow config is ok.

Netflow version 2.1
cacti 1.1.36
Ubuntu 16.04 LTS

**Comment by netniV** [comment]
This should be fixed in the development branch as per #22

**Comment by jpabloleon** [comment]
Hi, 

I installed Flowview on my Cactie hosts, with the recommendation to use development branch, however 
When applying a filter i see data, but no charts, like the print below, also de summary statistics filter doesn't work, Can anyone please help.


![filtergraph](https://user-images.githubusercontent.com/44270809/47800008-d4d16a80-dd01-11e8-81f0-ff70dc560504.png)

![statistics_summary](https://user-images.githubusercontent.com/44270809/47800066-ee72b200-dd01-11e8-8fb8-1c311ec6fe90.png)

Netflow version 2.1
cacti 1.1.38
Ubuntu 18.10 LTS

**Comment by netniV** [comment]
Please open that as a new issue

**Comment by jpabloleon** [comment]
ok thanks
