### ISSUE TITLE
Not Compatible, Requires: Cacti >= 1.2.28

### ISSUE THREAD

**Issue by neznoz** [Cacti/plugin_flowview#215]
My Cacti is currently version 1.2.27. Why is the plugin asking for version 1.2.28? I can't install the plugin right now. Please help, thank you.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by neznoz** [comment]
But My Cacti installation on Debian, not on Windows. What should i do?

**Comment by TheWitness** [comment]
I would upgrade to the latest 1.2.x branch.  It's just waiting for release.  We are moving slow at the moment.

```sh
cd /var/www/html/
git clone -b 1.2.x https://github.com/cacti/cacti.git cacti-new
cp -rp cacti-net/* cacti
chown -R apache:apache cacti
```

This assumes you did a source install.  If you are using packages, best wait for the package maintainer.  There are other options, but they can become complicated quickly.
