### ISSUE TITLE
Reports don't trigger when flowview is in a separate database

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#216]
It's on cacti 1.2.27 and Flowview 4.8.
My cacti db is on cacti
my Flowview DB is on flow_prod

I have this error on my brand new install:
`
11/09/2024  16:08:00 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview_process.php[97]:flowview_db_fetch_assoc(),  /plugins/flowview/database.php[166]:db_fetch_assoc(),  /lib/database.php[707]:db_fetch_assoc_prepared(),  /lib/database.php[727]:db_execute_prepared())
11/09/2024 16:08:00 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'flow_prod.reports_queued' doesn't exist
`

It's actually cause by a call on a table (reports_queued) that is not on the flowview scheme, but the function is used to call only flowview table.
Happen only if you flowview DB is not on Cacti DB.

**Comment by TheWitness** [comment]
The reports_queued should be in the Cacti database and not the flowview database.

**Comment by TheWitness** [comment]
Ugh, just reviewed the code.  Has to be changed.  Awesome!!

**Comment by TheWitness** [comment]
@arno-st , should be fixed now.  Please test.

**Comment by TheWitness** [comment]
Okay, all fixed now.  Found one more instance.  reports_queued is in the cacti database.
