### ISSUE TITLE
Can't dowload the external DB

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#220]
Hello,
I have an issue with Flowview, every night I have this error:

`
 ERROR PHP WARNING in Plugin 'flowview': file_get_contents(ftp://ftp.radb.net/radb/dbase//CANARIE.CURRENTSERIAL): Failed to open stream: operation failed in file: /usr/share/cacti/plugins/flowview/functions.php on line: 5806
`

And same for all DB that is supposed to download at midnight.

How can I solve this issue, since PHP has a config to go via a proxy:
$_SERVER['ftp_proxy'] => http://blablabla:8080/
$_SERVER['https_proxy'] => http://alsoblablabla:8080/
$_SERVER['http_proxy'] => http://alsoblablabla:8080/

I don't know if it's my setup, or a bug that has to be handle.

thanks for any help

**Comment by TheWitness** [comment]
So, where are those proxy settings coming from?

**Comment by arno-st** [comment]
php -info

But I can see the request on the firewall directly from the server

**Comment by TheWitness** [comment]
Okay, I've fixed this.  Please check under 'Mail/Reporting/DNS' for the setting, make the changes and then report back.

**Comment by arno-st** [comment]
Well,
not conclusive !
The security told me they can see a lot of access, on the proxy, to whois.arin.net
On the firewall, I can see some access on whois.radb.net on port 21 and irr-mirror.idnic.net

But not on the proxy

**Comment by arno-st** [comment]
Hello,
I see where you made your change.
You change are only used with the WHOIS query, inside 'flowview_get_owner_from_arin' with a call using curl

But the problem I have is on 'flowview_check_databases', where you download the ARIN files from different sources, and using 'file_get_content'

**Comment by TheWitness** [comment]
Can you do a pull request?

**Comment by arno-st** [comment]
All good now, I'm closing it.
