### ISSUE TITLE
Version requested for ORDER BY NATURAL_SORT_KEY(`key`)

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#223]
On the README you specify flowview is supported on MariaDB 8.5, but the ORDER BY NATURAL_SORT_KEY(`key`) is only available since MariaDB 10.7.

or is it possible to test the version and use a simple ORDER ?

Otherwise most views in Console -> FlowView -> Database are empty, but with a number of record.

**Comment by TheWitness** [comment]
I did not know that...  I don't think it's even supported in MySQL.  Let me fix that.

**Comment by TheWitness** [comment]
Pretty sure this is fixed now.  Please test and report back!

**Comment by arno-st** [comment]
[18-Dec-2024 16:50:53 Europe/Zurich] PHP Parse error:  Unmatched '}' in flowview/flowview_databases.php on line 743

You miss the open { on line 735

**Comment by arno-st** [comment]
And Line 27 it's utility.php

**Comment by TheWitness** [comment]
Well, that was a hack of course.  Let me throw it on my prod system.

**Comment by TheWitness** [comment]
Okay, test again :)

**Comment by TheWitness** [comment]
Test again again ;)

**Comment by arno-st** [comment]
All good thanks

**Comment by TheWitness** [comment]
Cool!
