### ISSUE TITLE
plugin not installable

### ISSUE THREAD

**Issue by publicocean0** [Cacti/plugin_flowview#23]
cacti 1.1.36
 gunzip -c plugin\:flowview-v1.1-1.tgz | tar xvf -

in console here is plugin with no info file. What to do?

**Comment by netniV** [comment]
That version is too old for Cacti 1.x, please use the 2.1 release.

**Comment by publicocean0** [comment]
ok it is installed . In installed also flowview tools in docker machine. I have to see my networking flow in the server . How to do? it is a simple howto?

**Comment by cigamit** [comment]
That would be a question for the forums, not for here.
