### ISSUE TITLE
Flowview problems

### ISSUE THREAD

**Issue by jpabloleon** [Cacti/plugin_flowview#24]
Hi,

I installed Flowview on my Cactie hosts, with the recommendation to use development branch, however
When applying a filter i see data, but no charts, like the print below, also de summary statistics filter doesn't work, Can anyone please help.

![filtergraph](https://user-images.githubusercontent.com/44270809/47803836-bc654e00-dd09-11e8-81c3-0872224830b4.png)

When i try statistics_summary filter no data is displayed like the print above.

![statistics_summary](https://user-images.githubusercontent.com/44270809/47803886-d737c280-dd09-11e8-9c73-a9b28afa4597.png)

Netflow version 2.1
cacti 1.1.38
Ubuntu 18.10 LTS

**Comment by jpabloleon** [comment]
I need help please i also tested in centos 7 but i have the same problems exactly the same.

**Comment by nvmike** [comment]
@jpabloleon - can you tell me how you reach this point ?
I did install the plugin in side of flow capture that is running - not able to see a thing - not even some statistic.

**Comment by jpabloleon** [comment]
You have to check with this command cat ft-v05.2018-10-31............. | flow-stat -f10 inside the folder where you selected to save flows, in my case is /var/flows/, if you don't see data maybe you should permit the port.

**Comment by jpabloleon** [comment]
@nvmike are you install in ubuntu?? or  centos???

**Comment by nvmike** [comment]
@jpabloleon - Installed on Centos7 - I have flow-stat - I do use this manually to create my report for the meaning time.
In cacti - I did point the misc conf to the right directory and set my listener accordingly ( directory only not full path) there are no error in the HTTP logs . I cannot understand what is going wrong.

You can see my conf on the issue #25

**Comment by jpabloleon** [comment]
@nvmike  the php version should be 7.1

**Comment by nvmike** [comment]
@jpabloleon - it is
PHP Version | 7.1.23

**Comment by jpabloleon** [comment]
@nvmike  sorry for not having more knowledge i cannot understand why is not working everything seems to be ok, maybe you could try to install in ubuntu, if you get it please tell me how do you get it.

Maybe this link could help you more than i do https://www.netadmin.com.tw/article_print.aspx?sn=1706070005 , in my case i cannot get the charts i am getting crazy :(

**Comment by nvmike** [comment]
@jpabloleon - Thank you for trying - I have one question: Did you do the optional configuration that is copying the customer flow-capture file into init.d ?
I did try this as well ( I do not understand why - regarding the fact I already have flow capture working properly ) but it was not permitting the service to come up .

**Comment by jpabloleon** [comment]
@nvmike  you must copy and check the correct path to your cacti.

**Comment by netniV** [comment]
Please note, that if this is a ubuntu/debian installation, there is a problem with charts as per https://github.com/Cacti/cacti/issues/2159

**Comment by jpabloleon** [comment]
@netniV In my case I tested with centos 7 also, and i have the same problem.

**Comment by netniV** [comment]
Unfortunately, I don't have a flowview device to test against, so I can't really do much more than suggest things at this time.

**Comment by nvmike** [comment]
I did give up - no idea why it is not working at all - I can see that when all seem to go to the right direction the flow-cat is not finding the file - no idea why it append a 0 to teh path:
[Sat Nov 10 18:44:42.087833 2018] [php7:notice] [pid 1082] [client 10.211.55.2:64018] PHP Notice:  Undefined offset: 0 in /var/www/html/cacti/plugins/flowview/flowview_devices.php on line 207, referer: http://10.211.55.9/cacti/plugins/flowview/flowview_devices.php?tab=listeners
flow-cat: Limit of 50 nested directories reached.
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0/0)
flow-cat: load_dir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0/0)
flow-cat: load_dir(): failed: Success
flow-cat: ftfile_loaddir(/var/flow/flow-tools/GCB/2018-11/2018-11-10/0): failed
flow-nfilter: ftiheader_read(): Warning, short read while loading header top.
flow-nfilter: ftiheader_read(): failed
flow-nfilter: ftio_init(): failed
flow-stat: ftiheader_read(): Warning, short read while loading header top.
flow-stat: ftiheader_read(): failed
flow-stat: ftio_init(): failed

**Comment by nvmike** [comment]
Just to be clear - I am able to manually flow-cat and flow-stat all my NetFlow captured in this directory.
So there is no problem of data collection at all .

**Comment by chris-y** [comment]
I have the same problem with the charts not displaying.
 
> Please note, that if this is a ubuntu/debian installation, there is a problem with charts as per [Cacti/cacti#2159](https://github.com/Cacti/cacti/issues/2159)

I deleted the link and put Chart.js 2.7.3 from the Cacti repo directly into include/js.  The charts still don't display, so it isn't that.

**Comment by chris-y** [comment]
Ah, they work in IE but not Edge, Firefox or Chrome (IE and Edge have other problems in that most of the options on the Filters tab don't display).  It appears that the charts are using "Open Flash Chart" which needs the Flash plugin, rather than Chart.js and HTML5...

Weirdly Edge isn't telling me that it has disabled Flash and offering to turn it on like it would do normally.

**Comment by netniV** [comment]
Yeah, it should probably try and use other charting libraries such as the Chart.js one (though we did recently find that Debian/Ubuntu blocks Cacti from having the latest version which is still outstanding).

**Comment by netniV** [comment]
Does anyone have a screenshot of what charts look like at the moment?

**Comment by chris-y** [comment]
They look like this (but with the bars labelled underneath which I've cut out for privacy):
![chart display](http://i68.tinypic.com/2nuoswh.jpg)

**Comment by netniV** [comment]
Do the colors represent anything or is that just alternating for visual effect?  Seems to be repeated rather than data source based.

**Comment by chris-y** [comment]
All the graphs are the same, so looks like five colours repeated rather than anything meaningful.

**Comment by hkdd** [comment]
I'm seeing the same behavior.  Chart.js version 2.7.3, no charts and summary report doesn't work.

**Comment by cigamit** [comment]
This plugin currently uses open flash charts.  Unfortunately flash support is dying.  Need someone to help get this thing moved to C3 or another library.

**Comment by netniV** [comment]
> I'm seeing the same behavior. Chart.js version 2.7.3, no charts and summary report doesn't work.

Whilst the plugin uses Chart.js, if it uses Chart.js that is included with the core, Debian/Ubuntu had an open bug report about their lack of update on that javascript library.  I haven't looked at the code but if it isn't included with the plugin, it may be worth doing so.

**Comment by cigamit** [comment]
I'm moving to either Chart.js or C3.js shortly.  Just got it working again in OpenFlashCharts, but it only works with Firefox at the moment.

**Comment by cigamit** [comment]
So, if you have Firefox, you can grab 2.2 right now and be back in business.

**Comment by netniV** [comment]
You should be able to still use Flash in chrome too, but it does require some extra steps of confirming that you want to use Flash despite them not wanting you to.

**Comment by cigamit** [comment]
This issue is resolved in the Development branch now.  We've moved to C3 charts.  Note that the summary distribution report is not functional.  If you want to test and report bugs, they will be responded to now.
