### ISSUE TITLE
Flowview not showing any info

### ISSUE THREAD

**Issue by nvmike** [Cacti/plugin_flowview#25]
Hello 
trying to have netflow through my Cacti - using 1.1.38 on Centos 7
I did configure flow-capture and run it : 
/usr/bin/flow-capture -D -n 287 -N -2 -w /var/flow-tools/GCB -S 5 0/10.70.1.254/9800

It is creating files accordingly:
/var/flow-tools/GCB/2018-11/2018-11-06/ft-v05.2018-11-06.095926+0000 

Cacti flowview directory of work:
![screen shot 2018-11-06 at 13 44 47](https://user-images.githubusercontent.com/19436894/48062273-3eea8380-e1ca-11e8-9649-9859b52bc6a6.png)

Listener:
![screen shot 2018-11-06 at 13 45 58](https://user-images.githubusercontent.com/19436894/48062340-604b6f80-e1ca-11e8-9df7-2f556ca28c97.png)

No error log in Apache - Nothing is showing in the filter pane.

Any idea where I am wrong ?

**Comment by cigamit** [comment]
This is likely your browser not supporting Flash.  We need someone to help us get this plugin moved to one of the JavaScript chart libraries included in Cacti.

**Comment by netniV** [comment]
ReportIt made use of one type of library.  The core has a separate one which doesn't always get updated with Cacti under Debian/Ubuntu.

**Comment by cigamit** [comment]
Flash was kind of broken.  It's fixed, but you will have to use Firefox until such time as we move to C3 or some other decent JavaScript based charting.
