### ISSUE TITLE
Flow Filter Constraints options not showing in IE/Edge

### ISSUE THREAD

**Issue by chris-y** [Cacti/plugin_flowview#26]
In the Filters tab, Flow Filter Constraints section, only the top two dropdowns (Filter and Listener) are displaying in IE and Edge.  In Chrome and Firefox the options are all displayed as expected.
Cacti 1.1.38 and FlowView current HEAD 45abca5

**Comment by cigamit** [comment]
Can you update and then show some example images of what you are experiencing?

**Comment by chris-y** [comment]
Unfortunately not as I stopped using it, but as per the initial report only the top two displayed, not the rest underneath.

**Comment by cigamit** [comment]
Just doing a major update.  It's been a while since I touched this plugin.  It was pretty broken.
