### ISSUE TITLE
Deprecated functions and legacy path causing issues with schedules

### ISSUE THREAD

**Issue by Stanymanman** [Cacti/plugin_flowview#27]
Hello,

I have error when I run a schedule task.
I have the impression the filter don't save the Listener in the query.

2019/03/05 09:45:48 - MAILER ERROR: Impossible d'accéder au fichier :
--
2019/03/05 09:45:48 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/flowview/flowview_schedules.php[109]:actions_schedules(), /plugins/flowview/flowview_schedules.php[153]:plugin_flowview_run_schedule(), /plugins/flowview/functions.php[364]:file_get_contents(), CactiErrorHandler())
2019/03/05 09:45:48 - ERROR PHP WARNING in Plugin 'flowview': file_get_contents(/opt/cacti/include/main.css): failed to open stream: No such file or directory in file: /opt/cacti/plugins/flowview/functions.php on line: 364
2019/03/05 09:45:46 - CMDPHP PHP ERROR Backtrace: (/plugins/flowview/flowview_schedules.php[109]:actions_schedules(), /plugins/flowview/flowview_schedules.php[166]:each(), CactiErrorHandler())
2019/03/05 09:45:46 - ERROR PHP DEPRECATED in Plugin 'flowview': The each() function is deprecated. This message will be suppressed on further calls in file: /opt/cacti/plugins/flowview/flowview_schedules.php on line: 166

Other problems : 
- the report parameter "Summary" give a blank page
- charts are displaying when flash is enabled for the site with Chrome but need to refresh the page to get it working

Thanks.

Ubuntu 18.04
Cacti 1.2.2
Flowview 2.1

**Comment by Stanymanman** [comment]
All is working with this install path:
- Install Cacti 1.1.17 / Flowview 2.1 / PHP 5.6
- Upgrade to Cacti 1.1.38 / Flowview 2.1 / PHP 5.6

But Upgrade to Cacti 1.2.2 / Flowview 2.1 / PHP 5.6 break the mailer with schedule task:
- MAILER ERROR : unable to acces file :

Something is broken between 1.1.38 and 1.2.2

Thanks.

**Comment by cigamit** [comment]
This is resolved now.
