### ISSUE TITLE
Not compatible with Cacti 1.0.4

### ISSUE THREAD

**Issue by righter83** [Cacti/plugin_flowview#3]
Hi

I upgraded my Cacti to 1.0.4 (version 1.0 should be supported from your plugin).
Then I have the error on the Plugin Management -> Plugin not compatible.

Cheers Righter

**Comment by cigamit** [comment]
Please pull the version from GitHub.  Older versions are not support on Cacti 1.0.x

**Comment by righter83** [comment]
damnit, I thought I fetched the newest version....
sorry about that
