### ISSUE TITLE
Error: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_flowview#30]
Ref: MySQL 5.5 and 5.6 Ref Manual:
 * https://dev.mysql.com/doc/refman/5.6/en/timestamp-initialization.html
 * https://dev.mysql.com/doc/refman/5.5/en/timestamp-initialization.html

Before MySQL 5.6, one table can not include two column with keyword `CURRENT_TIMESTAMP `

 * 2019/12/02  14:44:20 - CMDPHP SQL Backtrace:  (/index.php[24]:include(),  /include/auth.php[28]:require_once(),  /include/global.php[470]:include_once(),  /include/global_arrays.php[2697]:api_plugin_hook(),  /lib/plugins.php[74]:api_plugin_run_plugin_hook(),  /lib/plugins.php[177]:flowview_config_arrays(),  /plugins/flowview/setup.php[114]:plugin_flowview_check_upgrade(),  /plugins/flowview/setup.php[98]:flowview_setup_table(),  /plugins/flowview/setup.php[392]:api_plugin_db_table_create(),  /lib/plugins.php[464]:db_execute(),  /lib/database.php[191]:db_execute_prepared())
--
2019/12/02 14:44:20 - CMDPHP ERROR: A DB Exec Failed!, Error:  Incorrect table definition; there can be only one TIMESTAMP column with  CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```

**Comment by netniV** [comment]
Flowview is still work in progress at the moment so the develop branch is likely partially broken.  The simple fix is to remove the CURRENT_TIMESTAMP from everything but the updated field (assuming it has one) and the rest should be manually set anyway. 

This will likely be fixed in the next commit.

**Comment by cigamit** [comment]
Need to find about 3 good days to finish this.  After that, it'll be nice will work with v5, v9, and v10, and no other add-ons 'flow-tools' required.

**Comment by cigamit** [comment]
Pretty sure this is not an issue with the supported versions of the next flowview version that we are releasing.  So, I'm going to close this.
