### ISSUE TITLE
In systemctl status :  CMDPHP: ERROR: A DB Exec Failed!, Error: Unknown column 'INF' in 'field list'

### ISSUE THREAD

**Issue by JorisFRST** [Cacti/plugin_flowview#31]
systemctl status flow-capture
● flow-capture.service - Flow Capture Service for Cacti
   Loaded: loaded (/usr/lib/systemd/system/flow-capture.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-01-30 14:16:34 UTC; 20s ago
  Process: 2498 ExecStart=/usr/bin/php -q /var/www/html/cacti/plugins/flowview/service/flow-capture --systemd (code=exited, status=0/SUCCESS)
 Main PID: 2550 (php)
   CGroup: /system.slice/flow-capture.service
           └─2550 /bin/php -q /var/www/html/cacti/plugins/flowview/flow_collector.php --listener-id=1

Jan 30 14:16:33 va-beevecac01 systemd[1]: Starting Flow Capture Service for Cacti...
Jan 30 14:16:34 va-beevecac01 php[2498]: NOTE: Starting Flow Collection
Jan 30 14:16:34 va-beevecac01 php[2498]: PHP Notice:  Undefined variable: path in /var/www/html/cacti/plugins/flowview/service/flow-capture on line 55
Jan 30 14:16:34 va-beevecac01 php[2498]: NOTE: Launching cacti-flow-capture as '/var/www/html/cacti/plugins/flowview/flow_collector.php --listener-id=1'
Jan 30 14:16:34 va-beevecac01 systemd[1]: Started Flow Capture Service for Cacti.
Jan 30 14:16:52 va-beevecac01 Cacti[2550]: CMDPHP: ERROR: A DB Exec Failed!, Error: Unknown column 'INF' in 'field list'
Jan 30 14:16:53 va-beevecac01 Cacti[2550]: CMDPHP: ERROR: A DB Exec Failed!, Error: Unknown column 'INF' in 'field list'
Jan 30 14:16:54 va-beevecac01 Cacti[2550]: CMDPHP: ERROR: A DB Exec Failed!, Error: Unknown column 'INF' in 'field list'

**Comment by JorisFRST** [comment]
Latest commit aabe379

Can also see Undefined variable: path in /var/www/html/cacti/plugins/flowview/service/flow-capture on line 55 But I think that's not used anymore and should not affect ?

Also in cacti log :

2020/01/30 14:20:57 - CMDPHP SQL Backtrace: (/plugins/flowview/flow_collector.php[331]:process_fv5(), /plugins/flowview/flow_collector.php[439]:db_execute(), /lib/database.php[191]:db_execute_prepared())
--
2020/01/30 14:20:57 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'INF' in 'field list'
2020/01/30 14:20:57 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/flowview/flow_collector.php[331]:process_fv5(), /plugins/flowview/flow_collector.php[396]:CactiErrorHandler())
2020/01/30 14:20:57 - ERROR PHP WARNING in Plugin 'flowview': Division by zero in file: /var/www/html/cacti/plugins/flowview/flow_collector.php on line: 396

**Comment by cigamit** [comment]
Okay, I'm fixing a few of these.  I'm not sure about the INF column missing.  I'm guessing you are getting more than flow data coming into the port.  Maybe we need to verify that it's actually flow data.

**Comment by JorisFRST** [comment]
Thanks,

these errors are gone now.

- receiving v5 flows in the database now.  
- v9 I get sql errors. but have to make sure it is not my side first.

**Comment by cigamit** [comment]
I've corrected the data collector.  I added a few cacti_log messages.  Look for them, and report any new findings.

**Comment by JorisFRST** [comment]
I have not seen anything in the log referencing this after your update.
