### ISSUE TITLE
Netflow v9 - Netflow source not providing either prefix or nexthop information

### ISSUE THREAD

**Issue by JorisFRST** [Cacti/plugin_flowview#32]
Latest commit - a6ebf4a
MariaDB : 10.2.30-MariaDB MariaDB Server

2020/01/31 10:45:37 - CMDPHP SQL Backtrace: (/plugins/flowview/flow_collector.php[333]:process_fv9(), /plugins/flowview/flow_collector.php[650]:db_execute(), /lib/database.php[191]:db_execute_prepared())
2020/01/31 10:45:37 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' 0, 'spr-itunes', INET6_ATON("224.0.0.1"), 'all-systems.mcast.net', 'mcast.net',' at line 1
2020/01/31 10:45:37 - DBCALL ERROR: A DB Exec Failed!, Error: 1064, SQL: 'INSERT IGNORE INTO plugin_flowview_raw_202003010 (listener_id, engine_type, engine_id, sampling_interval, ex_addr, sysuptime, src_addr, src_domain, src_rdomain, src_as, src_if, src_prefix, src_port, src_rport, dst_addr, dst_domain, dst_rdomain, dst_as, dst_if, dst_prefix, dst_port, dst_rport, nexthop, protocol, start_time, end_time, flows, packets, bytes, bytes_ppacket, tos, flags) VALUES (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.254"), 'ip-10-101-161-254.private.net', 'private.net', 0, 25, , 0, 'spr-itunes', INET6_ATON("224.0.0.1"), 'all-systems.mcast.net', 'mcast.net', 0, 25, , 0, 'spr-itunes', NULL, 2, '2020-01-31 10:44:53.271', '2020-01-31 10:45:53.271', 1, 2, 64, 32, 192, 0), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 0, 'spr-itunes', INET6_ATON("239.255.255.250"), 'ip-239-255-255-250.private.net', 'private.net', 0, 1, , 0, 'spr-itunes', NULL, 2, '2020-01-31 10:45:01.420', '2020-01-31 10:45:54.919', 1, 2, 64, 32, 0, 0), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.103.22.254"), 'ip-10-103-22-254.private.net', 'private.net', 0, 6, , 0, 'spr-itunes', INET6_ATON("224.0.1.40"), 'cisco-rp-discovery.mcast.net', 'mcast.net', 0, 6, , 0, 'spr-itunes', NULL, 2, '2020-01-31 10:44:56.646', '2020-01-31 10:45:54.746', 1, 2, 64, 32, 192, 0), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 49733, 'dynamic', INET6_ATON("10.100.97.200"), 'va-beevenxt10.common.eu.corp.tada.com', 'tada.com', 0, 1, , 999, 'puprouter', NULL, 17, '2020-01-31 10:45:24.354', '2020-01-31 10:45:54.180', 1, 4, 4737, 1184.25, 0, 0), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 1227, 'dns2go', INET6_ATON("51.77.64.226"), 'ns31055923.ip-51-77-64.eu', 'ip-51-77-64.eu', 0, 1, , 443, 'https', NULL, 6, '2020-01-31 10:45:10.301', '2020-01-31 10:45:55.299', 1, 1, 41, 41, 0, 26), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("51.77.64.226"), 'ns31055923.ip-51-77-64.eu', 'ip-51-77-64.eu', 0, 29, , 443, 'https', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 29, , 1227, 'dns2go', NULL, 6, '2020-01-31 10:45:10.301', '2020-01-31 10:45:55.299', 1, 1, 52, 52, 0, 26), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.103.22.254"), 'ip-10-103-22-254.private.net', 'private.net', 0, 6, , 0, 'spr-itunes', INET6_ATON("224.0.0.13"), 'pim-routers.mcast.net', 'mcast.net', 0, 6, , 0, 'spr-itunes', NULL, 103, '2020-01-31 10:44:57.542', '2020-01-31 10:45:56.491', 1, 3, 174, 58, 192, 0), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 32378, 'unknown', INET6_ATON("44.44.88.230"), 'ip-44-44-88-230..net', '.net', 0, 1, , 8080, 'http-alt', NULL, 6, '2020-01-31 10:45:21.895', '2020-01-31 10:45:57.728', 1, 2, 80, 40, 0, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("44.44.88.230"), 'ip-44-44-88-230..net', '.net', 0, 6, , 8080, 'http-alt', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 6, , 32378, 'unknown', NULL, 6, '2020-01-31 10:45:21.895', '2020-01-31 10:45:57.728', 1, 2, 166, 83, 0, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 32297, 'unknown', INET6_ATON("40.67.254.36"), 'ip-40-67-254-36..net', '.net', 0, 1, , 443, 'https', NULL, 6, '2020-01-31 10:45:12.472', '2020-01-31 10:45:57.472', 1, 1, 41, 41, 0, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("40.67.254.36"), 'ip-40-67-254-36..net', '.net', 0, 2, , 443, 'https', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 2, , 32297, 'unknown', NULL, 6, '2020-01-31 10:45:12.472', '2020-01-31 10:45:57.472', 1, 1, 52, 52, 0, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 30461, 'unknown', INET6_ATON("44.44.88.230"), 'ip-44-44-88-230..net', '.net', 0, 1, , 8080, 'http-alt', NULL, 6, '2020-01-31 10:45:17.423', '2020-01-31 10:45:57.421', 1, 2, 138, 69, 0, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("44.44.88.230"), 'ip-44-44-88-230..net', '.net', 0, 6, , 8080, 'http-alt', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 6, , 30461, 'unknown', NULL, 6, '2020-01-31 10:45:17.423', '2020-01-31 10:45:57.421', 1, 1, 87, 87, 0, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 1368, 'screencast', INET6_ATON("44.44.88.117"), 'va-beevecac01.common.eu.corp.tada.com', 'tada.com', 0, 1, , 443, 'https', NULL, 6, '2020-01-31 10:45:07.529', '2020-01-31 10:45:57.410', 1, 39, 2939, 75.359, 0, 27), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("44.44.88.117"), 'va-beevecac01.common.eu.corp.tada.com', 'tada.com', 0, 21, , 443, 'https', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 21, , 1368, 'screencast', NULL, 6, '2020-01-31 10:45:07.529', '2020-01-31 10:45:57.410', 1, 246, 360721, 1466.346, 0, 27), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.100.201.62"), 'bezavhoisfb23.common.eu.corp.tada.com', 'tada.com', 0, 16, , 52982, 'dynamic', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 16, , 20002, 'commtact-http', NULL, 17, '2020-01-31 10:45:27.083', '2020-01-31 10:45:57.083', 1, 1557, 351182, 225.55, 184, 0), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 20002, 'commtact-http', INET6_ATON("10.100.201.62"), 'bezavhoisfb23.common.eu.corp.tada.com', 'tada.com', 0, 1, , 52982, 'dynamic', NULL, 17, '2020-01-31 10:45:27.083', '2020-01-31 10:45:57.083', 1, 76, 34025, 447.697, 184, 0), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.100.201.62"), 'bezavhoisfb23.common.eu.corp.tada.com', 'tada.com', 0, 16, , 5061, 'sip-tls', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 16, , 31716, 'unknown', NULL, 6, '2020-01-31 10:44:28.806', '2020-01-31 10:45:58.804', 1, 1, 40, 40, 96, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 31716, 'unknown', INET6_ATON("10.100.201.62"), 'bezavhoisfb23.common.eu.corp.tada.com', 'tada.com', 0, 1, , 5061, 'sip-tls', NULL, 6, '2020-01-31 10:44:28.806', '2020-01-31 10:45:58.804', 1, 2, 906, 453, 96, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 1284, 'iee-qfx', INET6_ATON("44.44.88.230"), 'ip-44-44-88-230..net', '.net', 0, 1, , 8080, 'http-alt', NULL, 6, '2020-01-31 10:45:28.188', '2020-01-31 10:45:58.074', 1, 12, 10090, 840.833, 0, 26), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("44.44.88.230"), 'ip-44-44-88-230..net', '.net', 0, 6, , 8080, 'http-alt', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 6, , 1284, 'iee-qfx', NULL, 6, '2020-01-31 10:45:28.188', '2020-01-31 10:45:58.074', 1, 9, 3116, 346.222, 0, 26), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("44.44.89.88"), 'beevehoipoc54.common.eu.corp.tada.com', 'tada.com', 0, 23, , 56668, 'dynamic', INET6_ATON("10.101.160.48"), 'ip-10-101-160-48.private.net', 'private.net', 0, 23, , 161, 'snmp', NULL, 17, '2020-01-31 10:45:12.219', '2020-01-31 10:46:02.667', 1, 3, 321, 107, 0, 0), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 7454, 'unknown', INET6_ATON("44.44.88.230"), 'ip-44-44-88-230..net', '.net', 0, 1, , 8080, 'http-alt', NULL, 6, '2020-01-31 10:45:18.482', '2020-01-31 10:46:03.480', 1, 1, 40, 40, 0, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("44.44.88.230"), 'ip-44-44-88-230..net', '.net', 0, 6, , 8080, 'http-alt', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 6, , 7454, 'unknown', NULL, 6, '2020-01-31 10:45:18.482', '2020-01-31 10:46:03.480', 1, 2, 2316, 1158, 0, 24), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 1, , 1318, 'krb5gatekeeper', INET6_ATON("172.217.17.142"), 'ams15s30-in-f14.1e100.net', '1e100.net', 0, 1, , 443, 'https', NULL, 6, '2020-01-31 10:44:53.941', '2020-01-31 10:46:05.1', 1, 7, 1389, 198.429, 0, 26), (2, 0, 0, 0, '10.101.161.6:51244', 698614, INET6_ATON("172.217.17.142"), 'ams15s30-in-f14.1e100.net', '1e100.net', 0, 11, , 443, 'https', INET6_ATON("10.101.161.6"), 'tme-a-b-1500556.common.eu.corp.tada.com', 'tada.com', 0, 11, , 1318, 'krb5gatekeeper', NULL, 6, '2020-01-31 10:44:53.941', '2020-01-31 10:46:05.1', 1, 10, 1093, 109.3, 0, 26)'
2020/01/31 10:45:37 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flow_collector.php[333]:process_fv9(), /plugins/flowview/flow_collector.php[624]:process_v9_v10(), /plugins/flowview/flow_collector.php[903]:CactiErrorHandler())
2020/01/31 10:45:37 - ERROR PHP NOTICE in Plugin 'flowview': Undefined offset: 15 in file: /var/www/html/cacti/plugins/flowview/flow_collector.php on line: 903
2020/01/31 10:45:37 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flow_collector.php[333]:process_fv9(), /plugins/flowview/flow_collector.php[624]:process_v9_v10(), /plugins/flowview/flow_collector.php[897]:CactiErrorHandler())
2020/01/31 10:45:37 - ERROR PHP NOTICE in Plugin 'flowview': Undefined offset: 13 in file: /var/www/html/cacti/plugins/flowview/flow_collector.php on line: 897
2020/01/31 10:45:37 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flow_collector.php[333]:process_fv9(), /plugins/flowview/flow_collector.php[624]:process_v9_v10(), /plugins/flowview/flow_collector.php[887]:CactiErrorHandler())
2020/01/31 10:45:37 - ERROR PHP NOTICE in Plugin 'flowview': Undefined offset: 9 in file: /var/www/html/cacti/plugins/flowview/flow_collector.php on line: 887

**Comment by cigamit** [comment]
Okay, that's good information.  Doing an update shortly.  Can you let us know the device type that is supplying the flow and the version?  Should be V9 of IPFIX (V10).

**Comment by cigamit** [comment]
Got the version from the header.  More coffee please!!!

**Comment by JorisFRST** [comment]
Thanks, that works.
