### ISSUE TITLE
cannot view flows

### ISSUE THREAD

**Issue by JorisFRST** [Cacti/plugin_flowview#33]
When opening the tab and selecting a filter :

(/plugins/flowview/flowview.php[55]:flowview_request_vars(), /plugins/flowview/flowview.php[324]:validate_store_request_vars(), /lib/html_utility.php[704]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
--

2020/01/31 16:41:23 - CMDPHP Validation Error, Variable:sortfield, Value:null Backtrace: (/plugins/flowview/flowview.php[55]:flowview_request_vars(), /plugins/flowview/flowview.php[324]:validate_store_request_vars(), /lib/html_utility.php[704]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
--
2020/01/31 16:41:20 - CMDPHP SQL Backtrace: (/plugins/flowview/flowview.php[26]:include_once(), /include/auth.php[28]:require_once(), /include/global.php[461]:include_once(), /include/global_arrays.php[2696]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:flowview_config_arrays(), /plugins/flowview/setup.php[153]:plugin_flowview_check_upgrade(), /plugins/flowview/setup.php[124]:flowview_setup_table(), /plugins/flowview/setup.php[451]:db_execute(), /lib/database.php[191]:db_execute_prepared())

If I comment line 55 in flowview.php it lets me select a filter but It will always revert the timespan to the previous or default setting.

**Comment by TheWitness** [comment]
Update to the latest develop.  This has been fixed.
