### ISSUE TITLE
recurring updates for plugin_flowview_ports

### ISSUE THREAD

**Issue by JorisFRST** [Cacti/plugin_flowview#34]
It looks like it tries to update plugin_flowview_ports regulary

2020/01/31 16:41:20 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry '10872' for key 'PRIMARY'
--
2020/01/31 16:41:20 - DBCALL ERROR: A DB Exec Failed!, Error: 1062, SQL: 'INSERT INTO `plugin_flowview_ports` VALUES (10872,'spr-itunes',0,'tcp','Shirt Pock

**Comment by TheWitness** [comment]
That only happens at install time.
