### ISSUE TITLE
Error when flowview raw tables do not exist

### ISSUE THREAD

**Issue by lilmike1464** [Cacti/plugin_flowview#35]
Installed Flowview 3.0, running Cacti 1.2.8. Under Configuration -> Settings -> Misc , there is only two options: 

Data Retention Policy 
Database partitioning Scheme 

I believe the directory stuff is supposed to be there but is missing. 

Let me know if there is any other info needed.

**Comment by TheWitness** [comment]
I think the directory stuff is completely replaced in that version.  Everything goes in the database.

**Comment by lilmike1464** [comment]
Ahh so if thats the case, there must be a different issue. 

I get:

DBCALL ERROR: A DB Cell failed!, Error 1146 SQL: 'SELECT COUNT(*) FROM plugin_flowview_raw_20200521 WHERE end_time >=?'

CMDPHP ERROR: A Cell DB Failed!, Error: Table 'cacti.plugin_flowview_raw_20200521' doesn't exist

I'm a network guy trying to get this up so any help would be appreciated!

**Comment by TheWitness** [comment]
Upload result of the MySQL command:

```sql
SHOW TABLES LIKE '%flowview%';
```

**Comment by TheWitness** [comment]
Update functions.php from Develop.  Should fix the issue.  Make sure you have properly setup the service so that it's inserting into the raw tables though.

**Comment by lilmike1464** [comment]
Thank for the help, turns out it was a permissions and iptables thing to start with. Now I'm seeing an error:

FUNCTION cacti.INET6_ATON does not exist and then after that a really long line for what looks like values that would be going into a table.

Error: 1305, SQL: 'INSERT IGNORE INTO...'

**Comment by TheWitness** [comment]
What version of MariaDB.  I think you will have to upgrade.  From my perspective, that's a key function.

**Comment by TheWitness** [comment]
Just checked.  You need MariaDB 10.0.12++.

**Comment by TheWitness** [comment]
Here is the link.  I'll update the README.md for Jimmy.

https://mariadb.com/kb/en/inet6_aton/
