### ISSUE TITLE
Creating Flowview filters fails

### ISSUE THREAD

**Issue by misterjmw** [Cacti/plugin_flowview#40]
Fresh install. Attempting to create a filter. No matter what is entered, saving fails.

[Here is a gif](https://i.imgur.com/8Lb0QBW.gif)

Error is:
````
Note, we could not process all your actions. Details are below.

SQL Save on table 'plugin_flowview_queries': Column 'device_id' does not exist, unable to save!
Save Successful.
````

**Comment by TheWitness** [comment]
I'll be correcting that today.  You will have to uninstall and re-install though.

**Comment by TheWitness** [comment]
Okay, update, re-install, restart and test again.

**Comment by misterjmw** [comment]
Uninstalled, reinstalled; No errors this time. But no filters created either. Verified permissions are correct.
[gif](https://i.imgur.com/eDM4j2i.gif)

**Comment by TheWitness** [comment]
Okay, just confirmed a few bugs from this side as well.  Guess I should have tried to create one myself.

**Comment by TheWitness** [comment]
Okay, should be fixed now.  Keep testing and keep those bugs and possible feature requests coming.  Let me know if you are getting data now.

**Comment by misterjmw** [comment]
This is working as expected now. Thank you @TheWitness
