### ISSUE TITLE
Enhancement - Unnecessary Dialog Box: "Opeartion Successful - Select a filter to display data."

### ISSUE THREAD

**Issue by misterjmw** [Cacti/plugin_flowview#41]
Is this dialog box necessary? It seems like the "Pick a Filter" note could be presented in a more efficient, less intrusive way.

![Filters-popup](https://user-images.githubusercontent.com/1383647/76795303-79850880-678e-11ea-8bce-fcf238bad10a.gif)

**Comment by TheWitness** [comment]
Okay, this is fixed now.
