### ISSUE TITLE
NaN and Division by Zero errors

### ISSUE THREAD

**Issue by sslayman** [Cacti/plugin_flowview#43]
I'm not sure if this is specific with Meraki but I get a lot of messages like this in the logs:
```
2020/04/15 15:02:30 - CMDPHP SQL Backtrace: (/plugins/flowview/flow_collector.php[337]:process_fv9(), /plugins/flowview/flow_collector.php[706]:db_execute(), /lib/database.php[210]:db_execute_prepared())
--
2020/04/15 15:02:30 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'NAN' in 'field list'
2020/04/15 15:02:30 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/flowview/flow_collector.php[337]:process_fv9(), /plugins/flowview/flow_collector.php[680]:process_v9_v10(), /plugins/flowview/flow_collector.php[1019]:CactiErrorHandler())
2020/04/15 15:02:30 - ERROR PHP WARNING in Plugin 'flowview': Division by zero in file: /usr/share/cacti/plugins/flowview/flow_collector.php on line: 1019
```
I was able to eliminate the error by adding by changing 
```
$pps = round($data[$fieldname['dOctets']] / $data[$fieldname['dPkts']], 3);
```
to 
```
if($data[$fieldname['dPkts']] > 0) {
	$pps = round($data[$fieldname['dOctets']] / $data[$fieldname['dPkts']], 3);
} else {
	$pps = 0;
}
```

**Comment by sslayman** [comment]
Similar issue here: plugins/flowview/functions.php on line: 2143

**Comment by TheWitness** [comment]
I think this fix is reasonable.

**Comment by TheWitness** [comment]
Fixed this, but wondering if it's working otherwise for you?

**Comment by sslayman** [comment]
Thank you! I am having an issue with it where I can see data in the sql
tables but somehow that data isn't showing right on the tab views. Still
trying to figure that out but otherwise it's been great!

**Comment by TheWitness** [comment]
There may still be bugs in the Filter logic.  Ensure that you select 'All' for protocols.  If you find any issue with the filtering, just update us with either a pull request, or an issue with enough detail (steps) for us to reproduce it.
