### ISSUE TITLE
FlowView tab missing

### ISSUE THREAD

**Issue by ultramekon** [Cacti/plugin_flowview#45]
Hi,

I am running a new install of cacti 1.1.38. I have installed the flowview plugin version2 and it shows as installed in the console. The setup then says:

"Next you have to setup your Cacti server as a FlowView sink from your various sources. Then, from FlowView -> Listeners, you must add the various listeners for all your flow-capture sources."

However, there is no FlowView tab in cacti. Am I missing a step?

Thanks

**Comment by TheWitness** [comment]
The minimum version would could be 1.2.  Not too sure.  Go into the permissions area for your account and see if you have the permissions.

**Comment by ultramekon** [comment]
Hi, my admin account has permissions, and I see Flow View settings under Misc. I just don't get the Flow View tab. The plugin installs and says it's for 1.x

**Comment by ultramekon** [comment]
![no_flowview](https://user-images.githubusercontent.com/7013655/80302806-34e48800-87a4-11ea-8458-33b02b886f37.JPG)

**Comment by ultramekon** [comment]
![image](https://user-images.githubusercontent.com/7013655/80302842-6c533480-87a4-11ea-8ddd-d09e3f428323.png)

**Comment by ultramekon** [comment]
![image](https://user-images.githubusercontent.com/7013655/80302863-8ab93000-87a4-11ea-8d21-f4fe88429cc2.png)

**Comment by ultramekon** [comment]
This is running on Ubuntu 18.04

**Comment by TheWitness** [comment]
Okay, that version of flowview were not going to be supporting any longer.  The new flowview 3.0 does not require flowtools for example.

**Comment by ultramekon** [comment]
OK. Is 3.0 available yet and what are the cacti version requirements please?

**Comment by TheWitness** [comment]
It's out there for testing.  You just need to download.  You can test on 1.1.38 by modifying the INFO. file

**Comment by ultramekon** [comment]
Thanks, I'll give it a go tomorrow

**Comment by ultramekon** [comment]
Nope, that didn't work. I edited the INFO file to allow it to install on a clean cacti, but see no settings or FlowView tab

**Comment by ultramekon** [comment]
Duh... noob error. 
Using older plugin as the latest version of cacti installed by Ubuntu is 1.1.38. Plugin was installed but not enabled. Working now, thanks.

**Comment by yusen107** [comment]
Hi ultramekon,

Can you share this flowview plugin of cacti v1.1.38 for me ?
![圖片 2](https://user-images.githubusercontent.com/71760509/93996294-a90f7000-fdc4-11ea-81dc-7c87c28cf692.jpg)


thanks.
