### ISSUE TITLE
flowData not show - 

### ISSUE THREAD

**Issue by andrebolzan** [Cacti/plugin_flowview#47]
Hello !

I using Cacti 1.2.11 with maria dba 10.x in CentOS 7

Tipo de servidor: MariaDB
Versão do servidor: 10.2.31-MariaDB - MariaDB Server
Versão do protocolo: 10

My flowview is version 3.0

the listener is up
[root@LAMP02-NOC ~]# netstat -ano | grep 2055
udp 213248 0 0.0.0.0:2055 0.0.0.0:* off (0.00/0/0)

the flowDATA not show in web interface (Flows)

i try query in database the and table is empty
SELECT printed, statistics, sortfield FROM plugin_flowview_queries

The Cacti log show this message:

01/May/2020 13:45:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flowview.php[61]:flowview_display_filter(), /plugins/flowview/functions.php[926]:CactiErrorHandler())
01/May/2020 13:45:23 - ERROR PHP NOTICE in Plugin 'flowview': Undefined index: id in file: /usr/share/cacti/plugins/flowview/functions.php on line: 926
01/May/2020 13:45:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flowview.php[61]:flowview_display_filter(), /plugins/flowview/functions.php[879]:CactiErrorHandler())
01/May/2020 13:45:23 - ERROR PHP NOTICE in Plugin 'flowview': Undefined index: id in file: /usr/share/cacti/plugins/flowview/functions.php on line: 879
01/May/2020 13:45:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flowview.php[61]:flowview_display_filter(), /plugins/flowview/functions.php[832]:CactiErrorHandler())
01/May/2020 13:45:23 - ERROR PHP NOTICE in Plugin 'flowview': Undefined index: id in file: /usr/share/cacti/plugins/flowview/functions.php on line: 832
01/May/2020 13:45:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flowview.php[59]:load_data_for_filter(), /plugins/flowview/functions.php[1245]:run_flow_query(), /plugins/flowview/functions.php[2151]:CactiErrorHandler())
01/May/2020 13:45:23 - ERROR PHP NOTICE in Plugin 'flowview': Undefined index: statistics in file: /usr/share/cacti/plugins/flowview/functions.php on line: 2151
01/May/2020 13:45:23 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM ( FROM plugin_flowview_raw_2020121 ) AS rs LIMIT 20' at line 1
01/May/2020 13:45:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flowview.php[59]:load_data_for_filter(), /plugins/flowview/functions.php[1245]:run_flow_query(), /plugins/flowview/functions.php[1918]:CactiErrorHandler())

Thnaks !

![flow_webInterface](https://user-images.githubusercontent.com/37314712/80823452-0f47ec00-8bb3-11ea-8e92-2cbc6a34cff7.png)
![FlowView Plugin](https://user-images.githubusercontent.com/37314712/80823455-1111af80-8bb3-11ea-880e-04bc5dddc635.png)

**Comment by TheWitness** [comment]
Please update to the latest flow_collector.php and report back.

**Comment by TheWitness** [comment]
I've confirmed that this is fixed now.
