### ISSUE TITLE
Division by zero errors viewing tables

### ISSUE THREAD

**Issue by formalhaut** [Cacti/plugin_flowview#53]
server: centos 7.4
cacti version:1.2.14
mariadb:10.3.24
flowview:3.0
i got info via cacti webconsole LOG tab:

CMDPHP  PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview.php[59]:load_data_for_filter(),  /plugins/flowview/functions.php[1247]:run_flow_query(),  /plugins/flowview/functions.php[2196]:CactiErrorHandler())
--
2020-09-16 10:17:54 - ERROR PHP WARNING in  Plugin 'flowview':  Division by zero in file:  /var/www/html/cacti-1.2.14/plugins/flowview/functions.php  on line: 2196

Any suggesions?

**Comment by TheWitness** [comment]
Well, the division by zero was a bug, that you have some other problems.  It's been pretty stable for a while, you just have to find out what you are doing wrong.
