### ISSUE TITLE
Windows Option? 

### ISSUE THREAD

**Issue by andermat8** [Cacti/plugin_flowview#54]
This may be a feature request as I'm not seeing any mention in the instructions regarding Windows.  Any way to get this working on a Windows server?  

Thank you

**Comment by TheWitness** [comment]
It should work, but you will have to do the service start/stop stuff yourself.  PHP for Windows have a number of function calls to install and start windows services.  You will have to play with that.  Once you have that worked out, issue a pull request.

Here are some tips...

https://stackoverflow.com/questions/5952500/setting-a-php-script-as-a-windows-service

**Comment by TheWitness** [comment]
@andermat8, were you able to get it working on Windows?  If so, do you have the changes documented?

**Comment by andermat8** [comment]
Nope.  As I recall, I was able to get the service created and it appeared to be running but it would crash.  I think it needs to run via cgywin but I got pulled into other projects and never revisited it.  We have a netflow app already, just wanted to see how it worked in Cacti as a potential cost saver.

**Comment by TheWitness** [comment]
Yea, it's not Enterprise class for sure.  The back end is SQL too, which makes certain queries run too long.  MariaDB has column store, and Spider storage.  But even with those issues resolved, it's still just a toy compared to other Enterprise solutions.

If I were still in the network space, it would have evolved well beyond where it is.  We have some other people helping now though.

**Comment by TheWitness** [comment]
I'm going to close this for now.  Windows is not a priority for me at the moment.
