### ISSUE TITLE
Netflow V9 Errors on CACTI

### ISSUE THREAD

**Issue by pbenner1974** [Cacti/plugin_flowview#55]
Hi,

I'm running CACTI 1.2.11 on Centos8 and Flowview 3.0, Database: 10.3.17-MariaDB MariaDB Server

My sending device is a Cisco ASR 1002X running IOX-XE 16.06.06

I am getting the following errors in Flowview and no data displays. I have verified that I am sending data and that the server is receiving it.

020/10/28  15:41:28 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[340]:process_fv9(),  /plugins/flowview/flow_collector.php[685]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1009]:CactiErrorHandler())
--
2020/10/28 15:41:28 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined offset: 21 in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1009
2020/10/28 15:41:28 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[340]:process_fv9(),  /plugins/flowview/flow_collector.php[685]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1008]:CactiErrorHandler())
2020/10/28 15:41:28 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined offset: 21 in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1008
2020/10/28 15:41:28 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[340]:process_fv9(),  /plugins/flowview/flow_collector.php[685]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1007]:CactiErrorHandler())
2020/10/28 15:41:28 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined offset: 22 in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1007
2020/10/28 15:41:28 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[340]:process_fv9(),  /plugins/flowview/flow_collector.php[685]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1006]:CactiErrorHandler())
2020/10/28 15:41:28 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined offset: 22 in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1006

Any ideas here. I am no programmer!

**Comment by TheWitness** [comment]
Who is the manufacturer of the device feeding the data and if a software based tool, please provide the name and version?

**Comment by TheWitness** [comment]
Okay, update the flow_collector.php and restart the service.

**Comment by TheWitness** [comment]
Seems odd that a modern Cisco device would not provide high precision timers.  But it does not matter.

**Comment by pbenner1974** [comment]
Updated. There is a new error


020/10/28  17:47:23 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[340]:process_fv9(),  /plugins/flowview/flow_collector.php[685]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1019]:CactiErrorHandler())
--
2020/10/28 17:47:23 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined variable: retime in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1019
2020/10/28 17:47:23 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[340]:process_fv9(),  /plugins/flowview/flow_collector.php[685]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1019]:CactiErrorHandler())
2020/10/28 17:47:23 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined variable: retime in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1019

**Comment by TheWitness** [comment]
Hehe, typo.

**Comment by TheWitness** [comment]
Grab another copy.

**Comment by pbenner1974** [comment]
I think that knocked it on the head. No data displaying but the errors are gone. I'll give it some time to collect.

Thank you for your help

**Comment by TheWitness** [comment]
You should be able to run the following command's:

```sql
SHOW TABLES LIKE 'plugin_flowview_raw%';
SELECT * FROM plugin_flowview_raw_2020301;
```

Assuming your first table has the 301 suffix.

**Comment by pbenner1974** [comment]
The table are present in the DB

MariaDB [cacti]> SHOW TABLES LIKE 'plugin_flowview_raw%';
+----------------------------------------+
| Tables_in_cacti (plugin_flowview_raw%) |
+----------------------------------------+
| plugin_flowview_raw_2020272            |
| plugin_flowview_raw_2020273            |
| plugin_flowview_raw_2020274            |
| plugin_flowview_raw_2020275            |
| plugin_flowview_raw_2020276            |
| plugin_flowview_raw_2020277            |
| plugin_flowview_raw_2020278            |
| plugin_flowview_raw_2020279            |
| plugin_flowview_raw_2020280            |
| plugin_flowview_raw_2020281            |
| plugin_flowview_raw_2020282            |
| plugin_flowview_raw_2020283            |
| plugin_flowview_raw_2020284            |
| plugin_flowview_raw_2020285            |
| plugin_flowview_raw_2020286            |
| plugin_flowview_raw_2020287            |
| plugin_flowview_raw_2020288            |
| plugin_flowview_raw_2020289            |
| plugin_flowview_raw_2020290            |
| plugin_flowview_raw_2020291            |
| plugin_flowview_raw_2020292            |
| plugin_flowview_raw_2020293            |
| plugin_flowview_raw_2020294            |
| plugin_flowview_raw_2020295            |
| plugin_flowview_raw_2020296            |
| plugin_flowview_raw_2020297            |
| plugin_flowview_raw_2020298            |
| plugin_flowview_raw_2020299            |
| plugin_flowview_raw_2020300            |
| plugin_flowview_raw_2020301            |
| plugin_flowview_raw_2020302            |
+----------------------------------------+
31 rows in set (0.001 sec)

and there is plenty of data, it is not presenting in Cacti though,

2020-10-29 00:01:00.000000 |     1 |       2 |        80 |            40 |   0 |     6 |
|     4290 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | ä+˚         | i--1-2-3--202._+g-122.+e+                                                           | _+g-122.+e+                              |      0 |      2 |          0 |    54267 | dy+a+ic         | O|>"     | i--79-124-62-34.79-_i-e.+e+                                                             | 79-_i-e.+e+                              |      0 |      2 |          0 |    57081 | dy+a+ic         |         |        6 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       1 |        40 |            40 |   0 |    20 |
|     4291 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | íX       | +++.a_b-_--b_e_+a+-_y.c-+                                                               | a_b-_--b_e_+a+-_y.c-+                    |      0 |      1 |          0 |    48152 | ++++-++         | ä+˚ã        | i--1-2-3-139._+g-122.+e+                                                           | _+g-122.+e+                              |      0 |      1 |          0 |       69 | +f+-            |         |       17 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       1 |        54 |            54 |   0 |     0 |
|     4292 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | ¢é}Z       | _ca++e_-13.ch1.ce+_y_-_ca++e_.c-+                                                       | ce+_y_-_ca++e_.c-+                       |      0 |      1 |          0 |    50016 | dy+a+ic         | ä+˘¿        | i--1-2-3-192._+g-122.+e+                                                           | _+g-122.+e+                              |      0 |      1 |          0 |    22345 | ++++-++         |         |        6 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       1 |        44 |            44 |   0 |     2 |
|     4293 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | æÉ@       | i--20-190-131-64.+_f+.+e+                                                               | +_f+.+e+                                 |      0 |      1 |          0 |      443 | h++-_           | JﬁR“       | 210.82.222.74.+-gic.+y                                                                  | +-gic.+y                                 |      0 |      1 |          0 |    64298 | dy+a+ic         |         |        6 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       1 |        40 |            40 |   0 |    17 |
|     4294 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | O|>"     | i--79-124-62-34.79-_i-e.+e+                                                             | 79-_i-e.+e+                              |      0 |      1 |          0 |    57081 | dy+a+ic         | ä+˚Ñ        | i--1-2-3-132._+g-122.+e+                                                           | _+g-122.+e+                              |      0 |      1 |          0 |    60456 | dy+a+ic         |         |        6 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       2 |        80 |            40 |   0 |     6 |
|     4295 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | JR/-     | _ca+-12i._had-+_e_+e_.-_g                                                               | _had-+_e_+e_.-_g                         |      0 |      1 |          0 |    59134 | dy+a+ic         | ä+¯|       | i--1-2-3-120._+g-122.+e+                                                           | _+g-122.+e+                              |      0 |      1 |          0 |      443 | h++-_           |         |        6 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       1 |        40 |            40 |   0 |     2 |
|     4296 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | ä+˚Ñ        | i--1-2-3--132._+g-122.+e+                                                           | _+g-122.+e+                              |      0 |      2 |          0 |    60456 | dy+a+ic         | O|>"     | i--79-124-62-34.79-_i-e.+e+                                                             | 79-_i-e.+e+                              |      0 |      2 |          0 |    57081 | dy+a+ic         |         |        6 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       1 |        40 |            40 |   0 |    20 |
|     4297 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | -+¶      | i--113-23-108-166.a-+ic-113.+e+                                                         | a-+ic-113.+e+                            |      0 |      1 |          0 |    51814 | dy+a+ic         | ä+¯O       | i--1-2-3-79._+g-122.+e+                                                            | _+g-122.+e+                              |      0 |      1 |          0 |       23 | +e++e+          |         |        6 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       1 |        40 |            40 |   0 |     2 |
|     4298 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | –Cﬁﬁ        | _e_-++e_1.--e+d+_.c-+                                                                   | --e+d+_.c-+                              |      0 |      1 |          0 |       53 | d-+ai+          | ä+˚(       | i--1-2-3-40._+g-122.+e+                                                            | _+g-122.+e+                              |      0 |      1 |          0 |    27839 | ++++-++         |         |       17 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       1 |       106 |           106 |   0 |     0 |
|     4299 |           1 |           0 |         0 |                 0 | 192.168.255.239:5 | 1319113400 | $-òÑ       | i--36-111-152-132.a-+ic-36.+e+                                                          | a-+ic-36.+e+                             |      0 |      1 |          0 |    59441 | dy+a+ic         | ä+˙a       | i--1-2-3-97._+g-122.+e+                                                            | _+g-122.+e+                              |      0 |      1 |          0 |    19277 | ++++-++         |         |        6 | 2020-10-29 00:01:00.000000 | 2020-10-29 00:01:00.000000 |     1 |       1 |        40 |            40 |   0 |     2 |

What is strange is that Cacti sees no listeners even though one is defined.
2020/10/29 09:20:25 - SYSTEM FLOWVIEW STATS: Time:2.0300 Listeners:0 Newrecs:0 Schedules:0

**Comment by pbenner1974** [comment]
Wanted to bump for any feedback if possible. I am so close!!

**Comment by TheWitness** [comment]
Been busy.  I'll spend a little time on Cacti stuff today.  Maybe I can find some time for this.

**Comment by TheWitness** [comment]
I fixed the listener total issue.

**Comment by TheWitness** [comment]
Marking this fixed now.
