### ISSUE TITLE
FlowView Data won't display in Cacti.

### ISSUE THREAD

**Issue by pbenner1974** [Cacti/plugin_flowview#57]
Hi,

I'm running CACTI 1.2.11 on Centos8 and Flowview 3.0, Database: 10.3.17-MariaDB MariaDB Server

My sending device is a Cisco ASR 1002X running IOX-XE 16.06.06

The error I receive in Cacti is: 

2020/11/03  06:50:49 - CMDPHP Validation Error, Variable:sortfield, Value:null  Backtrace:  (/plugins/flowview/flowview.php[49]:flowview_request_vars(),  /plugins/flowview/flowview.php[256]:validate_store_request_vars(),  /lib/html_utility.php[702]:die_html_input_error(),  /lib/html_validate.php[64]:cacti_debug_backtrace())
--
2020/11/03 06:50:48 - CMDPHP Validation Error, Variable:sortfield,  Value:null Backtrace:   (/plugins/flowview/flowview.php[49]:flowview_request_vars(),  /plugins/flowview/flowview.php[256]:validate_store_request_vars(),  /lib/html_utility.php[702]:die_html_input_error(),  /lib/html_validate.php[64]:cacti_debug_backtrace())

2020/11/03 06:50:48 - CMDPHP Validation Error, Variable:sortfield,  Value:null Backtrace:   (/plugins/flowview/flowview.php[49]:flowview_request_vars(),  /plugins/flowview/flowview.php[256]:validate_store_request_vars(),  /lib/html_utility.php[702]:die_html_input_error(),  /lib/html_validate.php[64]:cacti_debug_backtrace())

2020/11/03 06:50:46 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flowview.php[65]:flowview_display_filter(),  /plugins/flowview/functions.php[503]:CactiErrorHandler())
2020/11/03 06:50:46 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined index: ite in file:  /usr/share/cacti/plugins/flowview/functions.php  on line: 503

Thanks,

Phil

**Comment by pbenner1974** [comment]
Good Morning - Just wanted to bump this!

**Comment by pbenner1974** [comment]
Further errors in logs

2020/11/16  13:52:56 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[340]:process_fv9(),  /plugins/flowview/flow_collector.php[685]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1025]:flowview_get_dns_from_ip(),  /plugins/flowview/functions.php[3241]:db_execute_prepared())
--
2020/11/16 13:52:56 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'plugin_flowview_dnscache' is full

**Comment by TheWitness** [comment]
You need to increase your max_heap_table_size in MySQL and restart your database, or convert the table to InnoDB.

**Comment by TheWitness** [comment]
Ope, you mixed two bugs in one ticket.  I closed due to the database error.  Will keep it closed.  You will have to open a new ticket for the validation error.
