### ISSUE TITLE
Flowview 2.0 swfobject.js not loading

### ISSUE THREAD

**Issue by hackdefendr** [Cacti/plugin_flowview#6]
Unable to view charts or graphs in Flowview 2.0 on Cacti 1.1.5.

`Open Flash Chart

JSON Parse Error [Syntax Error]
Error at character 0, line 1:

0: `

**Comment by cigamit** [comment]
You will have to open the browser debug console.  Look for the callback and copy the response JSON and paste it here.  Also, is the Table view showing any data?

**Comment by cigamit** [comment]
I'm guessing this is due to a lack of data.  We need a volunteer to update the flash stuff to C3.js.  In the mean time, I'm just going to close this.  When you get issue #7 fixed, you won't have to worry about this one.

**Comment by hackdefendr** [comment]
This seems to work ok now that Issue #5 and Issue #7 were resolved.
