### ISSUE TITLE
create plugin_flowview_raw table faild 

### ISSUE THREAD

**Issue by c8900219** [Cacti/plugin_flowview#60]
Hello Everone
After I use this function, there will be errors when I want to create a temporary table. The information is as follows
log detail
2020/12/02 00:57:11 - CMDPHP SQL Backtrace: (/plugins/flowview/flowview_process.php[116]:db_fetch_cell_prepared(), /lib/database.php[402]:db_execute_prepared())
--
2020/12/02 00:57:11 - CMDPHP ERROR: A DB Cell Failed!, Error: Table 'cacti.plugin_flowview_raw_2020336' doesn't exist
2020/12/02 00:57:11 - CMDPHP SQL Backtrace: (/plugins/flowview/flowview_process.php[109]:get_tables_range(), /plugins/flowview/functions.php[3865]:create_raw_partition(), /plugins/flowview/functions.php[3662]:api_plugin_db_table_create(), /lib/plugins.php[468]:db_execute(), /lib/database.php[213]:db_execute_prepared())
2020/12/02 00:57:11 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'start_time`,`end_time`)) ENGINE = InnoDB COMMENT = 'Plugin Flowview - Details Re' at line 1

DB version mysql  Ver 15.1 Distrib 10.1.48-MariaDB, for Linux (aarch64) using readline 5.1

**Comment by cigamit** [comment]
Thanks, I have committed a fix for this issue.

**Comment by Christophe-kibale** [comment]
ERROR  PHP WARNING in  Plugin 'flowview': Invalid argument supplied for  foreach() in file: /var/www/html/cacti/plugins/flowview/functions.php   on line: 1310
--
2020/12/02 19:33:57 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview.php[65]:load_data_for_filter(),  /plugins/flowview/functions.php[1345]:purge_flowview_sessions(),  /plugins/flowview/functions.php[1310]:CactiErrorHandler())

**Comment by TheWitness** [comment]
I've done a light modification to the functions.php.  Just pull another copy.

**Comment by Christophe-kibale** [comment]
12/03/2020  08:31:56 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flow_collector.php[340]:process_fv9(),  /plugins/flowview/flow_collector.php[518]:unpack(), CactiErrorHandler())
--
12/03/2020 08:31:56 - ERROR PHP WARNING in  Plugin 'flowview':  unpack(): Type n: not enough input, need 2, have 0 in file:  /var/www/html/cacti/plugins/flowview/flow_collector.php  on line: 518

**Comment by Christophe-kibale** [comment]
2020/12/03  08:35:37 - CMDPHP SQL Backtrace:   (/plugins/flowview/flowview.php[65]:load_data_for_filter(),  /plugins/flowview/functions.php[1351]:run_flow_query(),  /plugins/flowview/functions.php[2167]:db_fetch_assoc(),  /lib/database.php[476]:db_fetch_assoc_prepared(),  /lib/database.php[490]:db_execute_prepared())
--
2020/12/03 08:35:37 - CMDPHP ERROR: A DB Row Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near 'AND  `protocol` IN (0,6,17,1,2,3,4,5,7,8,9) GROUP BY src_addr, dst_addr UNION  SEL' at line 1

**Comment by TheWitness** [comment]
We will need to see more of that query.  Is it reproducible?

**Comment by Christophe-kibale** [comment]
here is the request


Query     SELECT INET6_NTOA(src_addr) AS src_addr, INET6_NTOA(dst_addr) AS dst_addr, SUM(flows) AS flows, SUM(bytes) AS bytes, SUM(packets) AS packets, src_domain, dst_domain FROM (SELECT src_addr, dst_addr, SUM(flows) AS flows, SUM(bytes) AS bytes, SUM(packets) AS packets, src_domain, dst_domain FROM plugin_flowview_raw_2020338  AND `protocol` IN (0,6,17,1,2,3,4,5,7,8,9) GROUP BY src_addr, dst_addr) AS rs GROUP BY INET6_NTOA(src_addr), INET6_NTOA(dst_addr)  ORDER BY INET6_NTOA(1)  ASC LIMIT 10

**Comment by Christophe-kibale** [comment]
Test :

MariaDB [cacti]> SELECT INET6_NTOA(src_addr) AS src_addr, INET6_NTOA(dst_addr) AS dst_addr, SUM(flows) AS flows, SUM(bytes) AS bytes, SUM(packets) AS packets, src_domain, dst_domain FROM (SELECT src_addr, dst_addr, SUM(flows) AS flows, SUM(bytes) AS bytes, SUM(packets) AS packets, src_domain, dst_domain FROM plugin_flowview_raw_2020338  AND `protocol` IN (0,6,17,1,2,3,4,5,7,8,9) GROUP BY src_addr, dst_addr) AS rs GROUP BY INET6_NTOA(src_addr), INET6_NTOA(dst_addr)  ORDER BY INET6_NTOA(1)  ASC LIMIT 10;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND `protocol` IN (0,6,17,1,2,3,4,5,7,8,9) GROUP BY src_addr, dst_addr) AS rs GR' at line 1

**Comment by TheWitness** [comment]
Okay, perfect, thanks.

**Comment by Christophe-kibale** [comment]
> 
> 
> Okay, perfect, thanks.

I use cacti 1.2.15

**Comment by TheWitness** [comment]
These should be in separate tickets BTW.  It making tracing things much more difficult.  For the future, please create a new ticket.

**Comment by TheWitness** [comment]
Update the functions.php from flowview.  If you continue to get SQL Errors, open a new ticket.  Even though I've made changes, I had no clue how your queries are ending up like they are.
