### ISSUE TITLE
IPFIX Errors in Cacti Log

### ISSUE THREAD

**Issue by kubafalta** [Cacti/plugin_flowview#61]
Hi,

I'm running Cacti 1.2.4 on CentOS 7 with MariaDB 10.1.41 and Flowview 3.2.

Device sending IPFIX flows is Juniper SRX380 with JunOS 20.1R1-S2.

There is a lot of these messages in log:

2020/12/18  10:33:15 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[342]:process_fv10(),  /plugins/flowview/flow_collector.php[883]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1043]:CactiErrorHandler())
--
2020/12/18 10:33:15 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined offset: 2 in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1043
2020/12/18 10:33:15 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[342]:process_fv10(),  /plugins/flowview/flow_collector.php[883]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1043]:CactiErrorHandler())
2020/12/18 10:33:15 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined offset: 2 in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1043
2020/12/18 10:33:15 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[342]:process_fv10(),  /plugins/flowview/flow_collector.php[883]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1043]:CactiErrorHandler())
2020/12/18 10:33:15 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined offset: 2 in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1043
2020/12/18 10:33:15 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/flowview/flow_collector.php[342]:process_fv10(),  /plugins/flowview/flow_collector.php[883]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1043]:CactiErrorHandler())
2020/12/18 10:33:15 - ERROR PHP NOTICE in  Plugin 'flowview':  Undefined offset: 2 in file:  /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 1043

I can see some data but all of them have 0 Bytes and 0 Packets.

After couple of minutes it starts to log huge amount of these logs:

2020/12/18 10:44:21 - CMDPHP PHP ERROR WARNING Backtrace:  (/plugins/flowview/flow_collector.php[342]:process_fv10(), /plugins/flowview/flow_collector.php[758]:unpack(), CactiErrorHandler())
2020/12/18 10:44:21 - ERROR PHP WARNING in  Plugin 'flowview': unpack(): Type n: not enough input, need 2, have 0 in file: /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 758
2020/12/18 10:44:21 - CMDPHP PHP ERROR WARNING Backtrace:  (/plugins/flowview/flow_collector.php[342]:process_fv10(), /plugins/flowview/flow_collector.php[758]:unpack(), CactiErrorHandler())
2020/12/18 10:44:21 - ERROR PHP WARNING in  Plugin 'flowview': unpack(): Type n: not enough input, need 2, have 0 in file: /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 758
2020/12/18 10:44:21 - CMDPHP PHP ERROR WARNING Backtrace:  (/plugins/flowview/flow_collector.php[342]:process_fv10(), /plugins/flowview/flow_collector.php[758]:unpack(), CactiErrorHandler())
2020/12/18 10:44:21 - ERROR PHP WARNING in  Plugin 'flowview': unpack(): Type n: not enough input, need 2, have 0 in file: /usr/share/cacti/plugins/flowview/flow_collector.php  on line: 758

Then I have to delete the log because server runs out of space I restart service and situation is repeating.

Could you please help me to resolve it?

**Comment by TheWitness** [comment]
Awesome, each of the vendors implement things just a bit differently.  Don't have one of these things in my basement to receive a flow from unfortunately.

**Comment by TheWitness** [comment]
There is an easy workaround for the first issue, for the second, I need several minutes of your flow to be able to test from.

**Comment by TheWitness** [comment]
Looking at what is being provided, it's almost like there is a bug in the vendors flow.  That is the flow header.  Maybe you can find their flowview implementation documentation and share a link.

**Comment by TheWitness** [comment]
Pull the latest flow_collector.php from the develop branch, and then restart the flow-collector.  Once you do this, let it run until you start getting a bunch of Invalid header warnings and post them here.

**Comment by kubafalta** [comment]
I changed flow_collector.php and so far there isn't anz invalid header warnings. Now there is only this error in log when I display some data:


2020/12/18  19:46:01 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview.php[65]:load_data_for_filter(),  /plugins/flowview/functions.php[1350]:run_flow_query(),  /plugins/flowview/functions.php[2396]:CactiErrorHandler())
2020/12/18 19:46:01 - ERROR PHP WARNING in  Plugin 'flowview':  Division by zero in file:  /usr/share/cacti/plugins/flowview/functions.php  on line: 2396
2020/12/18 19:46:01 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview.php[65]:load_data_for_filter(),  /plugins/flowview/functions.php[1350]:run_flow_query(),  /plugins/flowview/functions.php[2396]:CactiErrorHandler())
2020/12/18 19:46:01 - ERROR PHP WARNING in  Plugin 'flowview':  Division by zero in file:  /usr/share/cacti/plugins/flowview/functions.php  on line: 2396
2020/12/18 19:46:01 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/flowview/flowview.php[65]:load_data_for_filter(),  /plugins/flowview/functions.php[1350]:run_flow_query(),  /plugins/flowview/functions.php[2396]:CactiErrorHandler())
2020/12/18 19:46:01 - ERROR PHP WARNING in  Plugin 'flowview':  Division by zero in file:  /usr/share/cacti/plugins/flowview/functions.php  on line: 2396

**Comment by TheWitness** [comment]
That's a symptom of the original problem.  I'll mask it for now.  But you are getting bogus flow data likely due to a defective flow from your Juniper.

**Comment by kubafalta** [comment]
I tried to change Juniper config to use version9 but now I can't see any flows in Flowview (I can see in Juniper log it is sending data).

 2020/12/18 21:04:56 - SYSTEM FLOWVIEW STATS: Time:0.0200 Listeners:1 Newrecs:0 Schedules:0 

I tried to retart flow-capture but there is still no data.

**Comment by TheWitness** [comment]
Is the cacti service running?

**Comment by TheWitness** [comment]
What about the cacti.log?  netstat on the listener port?

**Comment by kubafalta** [comment]
Yes, it is running.
I turn on debug in flow_collector.php and there is this information:

2020/12/18 21:38:11 - CMDPHP Flow: Cycle Time: 0.00
2020/12/18 21:38:11 - CMDPHP Flow: Data Found, Awaiting Templates
2020/12/18 21:38:11 - CMDPHP Flow: Processing v9 Data, Records: 10
2020/12/18 21:38:11 - CMDPHP Flow: Packet from: 10.1.3.65:50101 v9 - Len: 624
2020/12/18 21:38:11 - CMDPHP Flow: Sleep Time: 1.00
2020/12/18 21:38:11 - CMDPHP -----------------------------------------------

**Comment by TheWitness** [comment]
That does not look like ipfix.

**Comment by kubafalta** [comment]
That was after change on Juniper to use version9 (then I haven't any flows in Cacti as I wrote in previous comment).

When IPFIX was configured, output of debug in flow_collector was:


2020/12/18 22:35:59 - CMDPHP Flow: Cycle Time: 0.01
2020/12/18 22:35:59 - CMDPHP Flow: Writing Records: 9
2020/12/18 22:35:59 - CMDPHP Flow: Data Found, Processing
2020/12/18 22:35:59 - CMDPHP Flow: Processing v10/IPFIX Data, Len: 632
2020/12/18 22:35:59 - CMDPHP Flow: Packet from: 10.1.3.65:50101 v10 - Len: 632
2020/12/18 22:35:59 - CMDPHP Flow: Sleep Time: 0.98
2020/12/18 22:35:59 - CMDPHP -----------------------------------------------
2020/12/18 22:35:58 - CMDPHP Flow: Cycle Time: 0.03
2020/12/18 22:35:58 - CMDPHP Flow: Writing Records: 5
2020/12/18 22:35:58 - CMDPHP Flow: Data Found, Processing
2020/12/18 22:35:58 - CMDPHP Flow: Processing v10/IPFIX Data, Len: 360
2020/12/18 22:35:58 - CMDPHP Flow: Packet from: 10.1.3.65:50101 v10 - Len: 360
2020/12/18 22:35:58 - CMDPHP Flow: Sleep Time: 0.86
2020/12/18 22:35:58 - CMDPHP -----------------------------------------------
2020/12/18 22:35:57 - CMDPHP Flow: Cycle Time: 0.03
2020/12/18 22:35:57 - CMDPHP Flow: Writing Records: 21
2020/12/18 22:35:57 - CMDPHP Flow: Data Found, Processing
2020/12/18 22:35:57 - CMDPHP Flow: Processing v10/IPFIX Data, Len: 1448
2020/12/18 22:35:57 - CMDPHP Flow: Packet from: 10.1.3.65:50101 v10 - Len: 1448
2020/12/18 22:35:57 - CMDPHP Flow: Sleep Time: 0.00
2020/12/18 22:35:57 - CMDPHP -----------------------------------------------

**Comment by kubafalta** [comment]
That was after change on Juniper to use version9 (then I haven't any flows in Cacti as I wrote in previous comment).

When IPFIX was configured, output of debug in flow_collector was:


2020/12/18 22:35:59 - CMDPHP Flow: Cycle Time: 0.01
2020/12/18 22:35:59 - CMDPHP Flow: Writing Records: 9
2020/12/18 22:35:59 - CMDPHP Flow: Data Found, Processing
2020/12/18 22:35:59 - CMDPHP Flow: Processing v10/IPFIX Data, Len: 632
2020/12/18 22:35:59 - CMDPHP Flow: Packet from: 10.1.3.65:50101 v10 - Len: 632
2020/12/18 22:35:59 - CMDPHP Flow: Sleep Time: 0.98
2020/12/18 22:35:59 - CMDPHP -----------------------------------------------
2020/12/18 22:35:58 - CMDPHP Flow: Cycle Time: 0.03
2020/12/18 22:35:58 - CMDPHP Flow: Writing Records: 5
2020/12/18 22:35:58 - CMDPHP Flow: Data Found, Processing
2020/12/18 22:35:58 - CMDPHP Flow: Processing v10/IPFIX Data, Len: 360
2020/12/18 22:35:58 - CMDPHP Flow: Packet from: 10.1.3.65:50101 v10 - Len: 360
2020/12/18 22:35:58 - CMDPHP Flow: Sleep Time: 0.86
2020/12/18 22:35:58 - CMDPHP -----------------------------------------------
2020/12/18 22:35:57 - CMDPHP Flow: Cycle Time: 0.03
2020/12/18 22:35:57 - CMDPHP Flow: Writing Records: 21
2020/12/18 22:35:57 - CMDPHP Flow: Data Found, Processing
2020/12/18 22:35:57 - CMDPHP Flow: Processing v10/IPFIX Data, Len: 1448
2020/12/18 22:35:57 - CMDPHP Flow: Packet from: 10.1.3.65:50101 v10 - Len: 1448
2020/12/18 22:35:57 - CMDPHP Flow: Sleep Time: 0.00
2020/12/18 22:35:57 - CMDPHP -----------------------------------------------

**Comment by kubafalta** [comment]
So from flowview side there is nothing what can be done and problem is on Juniper in data format which is sending?

**Comment by TheWitness** [comment]
What is happening now in the case of errors?

**Comment by kubafalta** [comment]
I think you did some change to hide these errors as you commented on 18th of December so there aren't the same erorrs as in December.
But there are still just zero values in columns Bytes and Paclets.

And now there is a new error in log but it is probably different problem:

2021/01/06  15:16:57 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[342]:process_fv10(),  /plugins/flowview/flow_collector.php[890]:process_v9_v10(),  /plugins/flowview/flow_collector.php[1032]:flowview_get_dns_from_ip(),  /plugins/flowview/functions.php[3292]:db_execute_prepared())
2021/01/06 15:16:57 - CMDPHP ERROR: A DB Exec Failed!, Error: The table 'plugin_flowview_dnscache' is full

Is the maximum of rows 24570?


Jakub

**Comment by TheWitness** [comment]
It's doing it in a heap table.  So, you have two options:

1. Convert the table to InnoDB
2. Increase your 'max_heap_table_size' in /etc/my.cnf.d/server.cnf and restart MariaDB

I'd go with 1.

```sql
ALTER TABLE plugin_flowview_dnscache ENGINE=InnoDB;
```

**Comment by kubafalta** [comment]
Thank you, it is ok now.

So the last problem is no Bytes and Packtes data but if it is due to bad format of data which Juniper is sendind I'll ask Juniper support.

**Comment by TheWitness** [comment]
Get them to provide a link to their specs.

**Comment by kubafalta** [comment]
I found this: https://www.juniper.net/documentation/en_US/junos/topics/topic-map/ipfix-formatting-for-srx-jflow.html
Is it helpful?

**Comment by kubafalta** [comment]
Hi,
Would it be possible to resolve it somehow with on url which I posted in January?
Thanks.

**Comment by TheWitness** [comment]
@kubafalta, I've finally been able to resolve the issues with IPFIX working with @xmacan in the last week.  Marking this resolved and closing.  I suggest you download the latest develop and test again.  If you find an issue, open a new bug.
