### ISSUE TITLE
Flowview disappears from Cacti GUI

### ISSUE THREAD

**Issue by ericfretz** [Cacti/plugin_flowview#64]
I have the latest released version of flowview (v3.2) installed under Cacti 1.2.16 running on Ubuntu 20.04.2 LTS.

My problem is that after installing the Flowview plugin, I can see "Flows" on the top of the Cacti webpage, but after I go through the steps to create flow listeners, the "flow" link will disappear from the top of the Cacti webpage.  I have verified that flowplugin is enabled and installed, but I can no longer see "Flows" at the top of the GUI and can no longer access the flow settings.  Uninstalling and reinstalling the plugin will return the links to view the flows and flow configuration, but they will disappear soon after enabling listeners.

**Comment by ericfretz** [comment]
![image](https://user-images.githubusercontent.com/77069836/113611158-bf1fa800-9613-11eb-85af-312eef932a98.png)

**Comment by ericfretz** [comment]
If it is relevant, I am also seeing the following lines repeated in the cacti logs:


2021/04/05 11:35:26 - FLOWVIEW WARNING: Field length not set for name:flowEndSysUpTime, id: 21 has length 4
2021/04/05 11:35:26 - FLOWVIEW WARNING: Field length not set for name:flowStartSysUpTime, id: 22 has length 4
2021/04/05 11:35:26 - FLOWVIEW WARNING: Field length not set for name:egressInterface, id: 14 has length 2
2021/04/05 11:35:26 - FLOWVIEW WARNING: Field length not set for name:ingressInterface, id: 10 has length 2
2021/04/05 11:35:26 - FLOWVIEW WARNING: Field length not set for name:packetDeltaCount, id: 2 has length 4
2021/04/05 11:35:26 - FLOWVIEW WARNING: Field length not set for name:octetDeltaCount, id: 1 has length 4
2021/04/05 11:35:26 - FLOWVIEW WARNING: Field length not set for name:destinationTransportPort, id: 11 has length 2
2021/04/05 11:35:26 - FLOWVIEW WARNING: Field length not set for name:sourceTransportPort, id: 7 has length 2

**Comment by ericfretz** [comment]
I have discovered more logs that might highlight what's goin on:


2021/04/05 13:16:30 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'flowview'
2021/04/05 13:16:30 - ERROR PHP ERROR in Plugin 'flowview': Uncaught Error: Call to undefined function curl_init() in /opt/cacti/plugins/flowview/functions.php:3529 Stack trace: #0 /opt/cacti/plugins/flowview/functions.php(3287): flowview_get_owner_from_arin() #1 /opt/cacti/plugins/flowview/flow_collector.php(1028): flowview_get_dns_from_ip() #2 /opt/cacti/plugins/flowview/flow_collector.php(685): process_v9_v10() #3 /opt/cacti/plugins/flowview/flow_collector.php(340): process_fv9() #4 {main} thrown in file: /opt/cacti/plugins/flowview/functions.php on line: 3529

The reason flowview disappears from the GUI is because the plugin is getting disabled by Cacti

**Comment by cigamit** [comment]
Seems you don't have php-curl installed?

**Comment by ericfretz** [comment]
Yep, that's it.  I just did  _sudo apt install php-curl_ and it cleared that particular issue.
