### ISSUE TITLE
error install Flowview plugin. please help

### ISSUE THREAD

**Issue by komarovaa** [Cacti/plugin_flowview#67]
Good day!
Installed Cacti version 1.2.18. downloaded the flowview plugin version 3.2. mysql  Ver 15.1 Distrib 10.3.29-MariaDB. When I try to include it in the webgui, it writes an error to the log

`2021-07-08 13:49:29 - CMDPHP SQL Backtrace: (/plugins.php[74]:api_plugin_install(), /lib/plugins.php[671]:db_execute_prepared())
2021-07-08 13:49:29 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'name' cannot be null`

Has anyone encountered such a problem? please tell me how you can solve

**Comment by netniV** [comment]
This suggests some weird issue where your plugin didn't return it's name.  Was there any other errors (bit late I know)

**Comment by arktronic** [comment]
I just ran into the same issue. Turns out, when Cacti suggests you name the plugin directory `Flowview`, that's incorrect. It needs to be named `flowview`. The capitalization change fixes this name error.

**Comment by cigamit** [comment]
Cacti doesn't suggest what to name the plugin's directory.  It's just telling you the actual human-readable name of the plugin.
