### ISSUE TITLE
Flowview top tab missing?

### ISSUE THREAD

**Issue by whitty** [Cacti/plugin_flowview#68]
Apologies if this is PEBCAK - i saw #45 which sounds similar, but is based on older versions.

**Describe the bug**
After installing and enabling `flowview` plugin and enabling a listener, verifying flowcollector service is running and listener reports Status == "Up" I was expecting to be able to configure or visualise flows - or _something_.

According to this video https://youtu.be/eIpoK0nFgR8?t=372 I saw there is a "FlowView" tab in the top - I do not see anything.  I have the flowview entry in the "console" at left, but not at the top..

![image](https://user-images.githubusercontent.com/194537/133605715-be6f7681-a72c-40ec-b721-5a061973f7f5.png)

Its probably something I don't understand - I've used cacti for about 3 days at this point.
 

**To Reproduce**

1. Install cacti and flowview plugin according to these instructions https://github.com/QuantumObject/docker-cacti (also exposing port 2055 UDP)
2. Enable the plugin
3. Configure the listener as global (defaults - listening on 0.0.0.0:2055)
4. Start the flow-capture service `/usr/bin/php -q /var/www/html/cacti/plugins/flowview/service/flow-capture start` 
5. Verify global listener is up
6. Ensure router is configured to direct flowview to cacti IP address (Ubiquiti EdgeRouter Lite)
7. Look around for any way to see flowview do anything?

Alternate step 4
4.1 Check the listener ID on the flow_collector.php and start `flow_collector.php --debug --listener-id=<id>` manually to get debug info
4.2 Verify that packets are being received and processed -eg:

```
-----------------------------------------------
Flow: Sleep Time: 0.00
Flow: Packet from: 192.168.1.1:46932 v10 - Len: 500
Flow: Processing v10/IPFIX Data, Len: 500
Flow: Data Found, Processing
Flow: Writing Records: 8
Flow: Cycle Time: 0.01
```

**Expected behavior**

Either - A FlowView tab will be visible at the top of the screen like in the video above

OR - there would be some other way to visualise or or preview the incoming data from the router.  Or create reports, or anything?  I may have missed where the data would be made available.

All I can see is in the "console" at left the ability to configure "Filters" and "Schedules" but adding one or the other doesn't suddednly show a new data source or graph source, or device or any other way to start visualising anything.

**Screenshots**

I was expecting a tab at the top - but there is nothing:

![image](https://user-images.githubusercontent.com/194537/133605715-be6f7681-a72c-40ec-b721-5a061973f7f5.png)

**Plugin (please complete the following information):**
 - Version: 3,2
 - Source: github /develop branch
 - Identifer: c0993331a7dce524a9618d838e6f34b77a1acf2b
 
**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 91.0.2

**Additional context**

Cacti version: Version 1.2.16

Server is running from docker image `QuantumObject/docker-cacti`:
 https://github.com/QuantumObject/docker-cacti/blob/master/Dockerfile

Modified to run `flow-capture` service under `runit`.  Also verified by manually starting `flow_collector.php --debug`

**Comment by TheWitness** [comment]
Ensure you user has the flow viewer permission.

**Comment by whitty** [comment]
Thanks for the response - I am admin, and I assume this is right:

![image](https://user-images.githubusercontent.com/194537/133697112-dcc3434d-912f-4330-b32c-ac4d591602ce.png)

**Comment by whitty** [comment]
Sorry - if last response wasn't clear - the permission was already set.

**Comment by TheWitness** [comment]
See it the plugin is enabled.

**Comment by whitty** [comment]
I'm so sorry to waste your time - you are correct - I believe my confusion was twofold:

![image](https://user-images.githubusercontent.com/194537/133923563-e367870a-3d5d-4672-8bfc-d246c9780960.png)

1. The red looked like a disablement, so I hit it.  It turned green.
2.  I assumed that was enabled right because I was able to get the listener into the up state, and the configuration was available.

(PS I work on a media player and we have a similar problem with play/pause - if its a button/touchable you show Play when paused and Pause when playing.  If its an indicator you reverse it).
