### ISSUE TITLE
no data in FlowView

### ISSUE THREAD

**Issue by ISekan** [Cacti/plugin_flowview#70]
Cacti 1.2.19
MariaDB 10.2.33
Centos7
PHP 7.3.22

Plugin installed and started 
flow-capture service wokrs normal 
Listener started 
[appadmin@srv-mncacti-01 ~]$ sudo tcpdump -vv -i ens192 udp port 9996
tcpdump: listening on ens192, link-type EN10MB (Ethernet), capture size 262144 bytes
13:51:18.333494 IP (tos 0x0, ttl 254, id 0, offset 0, flags [none], proto UDP (17), length 1432)
    10.241.254.13.safetynetp > srv-mncacti-01.best.local.palace-5: [no cksum] UDP, length 1404
13:51:18.471380 IP (tos 0x0, ttl 254, id 0, offset 0, flags [none], proto UDP (17), length 1432)
    10.241.254.13.safetynetp > srv-mncacti-01.best.local.palace-5: [no cksum] UDP, length 1404
13:51:18.480332 IP (tos 0x0, ttl 254, id 0, offset 0, flags [none], proto UDP (17), length 1432)

but no data in FlowView

is there any log?

**Comment by TheWitness** [comment]
Is this an upgrade from a prior version?  If so, uninstall the old version, then drop all the "%flow%" tables, and then install the new version.  Here is the schedules schema.

![image](https://user-images.githubusercontent.com/1439914/147251313-e4064d31-1b80-45c6-8f61-9af6e957829b.png)

**Comment by TheWitness** [comment]
I believe there is a script to "import" the old data, it's been a while though.  It's called `import_flows.php`.  This is for the case where you had the old version and have a number of flow files from the old flowview plugin.

**Comment by Izmenoff** [comment]
No it's a new install

**Comment by ISekan** [comment]
It's a new installation and after some time the flow has started
Thanks, TheWitness
