### ISSUE TITLE
Flowview no data were displayed after empty or defined filter

### ISSUE THREAD

**Issue by tomowaw** [Cacti/plugin_flowview#74]
**Describe the bug**
Hi,

I'm trying to display flowview (v5) from one network device but no data is displayed.
Tried to run flowview on CentOS 7 nad Ubuntu 20.04 with newest Cacti 1.2.20.
Fresh installation is Ubuntu 20.04, Apache 2 (2.4.41), PHP 7.4.3, MariaDB 10.3.34.
Cacti runs without Pollers and there is no defined Devices (no SNMP). Clean installation.

FlovView was downloded 3.3 (latest release). Untar. Moved to /var/www/html/cacti/plugins/flowview
Service was copied and enabled (running and listening on port 2055)

New files with bugfixex (develop) was copied to plugin : flowview.php and functions.php
Still same problem.

**To Reproduce**
1. Cacti 1.2.20
2. Flowview 3.3
3. service running (flow-capture)
4. Plugin installed & enabled
5. nestat -an | grep 2055
6. Console -> Configuration -> Settings -> Misc (default option, 'save' button didn't change anything)
7. Console -> FlowView -> Listener -> Add (new) name, IP address, port 2055
8. Filters on screen
9. No schedule change (empty)
10. Logs -> errors

2022-04-27 14:10:53 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/flowview/flowview.php[50]:flowview_get_chartdata(), /plugins/flowview/functions.php[1530]:CactiErrorHandler())
--
2022-04-27 14:10:53 - ERROR PHP NOTICE in Plugin 'flowview': Trying to access array offset on value of type bool in file: /var/www/html/cacti/plugins/flowview/functions.php on line: 1530

Thanks for help

![flowview_case_01](https://user-images.githubusercontent.com/20935414/165519151-3eca0518-d922-4a3d-ad9e-1f527c342126.PNG)
![flowview_case_02](https://user-images.githubusercontent.com/20935414/165519161-0424e0b3-02e9-4305-9a03-edf92755f52e.PNG)
![flowview_case_03](https://user-images.githubusercontent.com/20935414/165519163-20bd822d-e2ce-4655-bea3-8ac8aad735cf.PNG)
![flowview_case_04](https://user-images.githubusercontent.com/20935414/165519165-fe49b1a0-f0bf-4734-a13c-691e824c424e.PNG)
![flowview_case_05](https://user-images.githubusercontent.com/20935414/165519169-585af314-142e-43e7-909c-8fb113ff1bb4.PNG)
![flowview_case_06](https://user-images.githubusercontent.com/20935414/165519172-8a8d1217-65fe-432d-86db-d84daeede8be.PNG)
![flowview_case_07](https://user-images.githubusercontent.com/20935414/165519174-c0f6ac46-d74e-464f-beec-829e41d15bf5.PNG)
![flowview_case_08](https://user-images.githubusercontent.com/20935414/165519179-00b94aaf-0299-4a0a-b028-876ada7c34a2.PNG)
![flowview_case_09](https://user-images.githubusercontent.com/20935414/165519184-03a9573e-7c2f-4eed-b283-e85b25bfb3f3.PNG)
![flowview_case_10](https://user-images.githubusercontent.com/20935414/165519185-72e8a524-c67a-4c7a-991e-1868f0548b80.PNG)
![flowview_case_11](https://user-images.githubusercontent.com/20935414/165519192-4fdddec8-ffd6-4a68-b8f0-912e92c47042.PNG)
![flowview_case_12](https://user-images.githubusercontent.com/20935414/165519196-7ede7bf1-ef6f-4f22-8488-6331a96656eb.PNG)

**Comment by TheWitness** [comment]
It's likely that the filter is returning no data.  There could be a problem with the Filter on the IP, or you are not including enough protocols.  I've fixed the small error, but keep working on the Filter.  If you want to see the SQL, you can go into that function and `cacti_log()` the SQL before the `db_fetch_assoc()` call.

**Comment by tomowaw** [comment]
Thanks for fix. Error was gone.
I will check filter options.

**Comment by tomowaw** [comment]
After changing IP in Filter (all subnet) flowview displays data.
Thanks for help and resolving issue with error in log.

![flowview_case_15](https://user-images.githubusercontent.com/20935414/165723687-8e8af5df-5d62-4187-8008-85db13a9576c.PNG)

**Comment by TheWitness** [comment]
MySQL/MariaDB include a whole set of IP address filtering functions and store the IP Address information in binary form to facilitate those functions.  That's why when you look at the actual tables, the data is stored in a binary format.  Glad you figured it out.
