### ISSUE TITLE
PHP 8.1 error heartbeat float 5.5 precision

### ISSUE THREAD

**Issue by luistriunfo** [Cacti/plugin_flowview#76]
Hi!
I installed Cacti a few days ago. Everything works correctly but in the log this appears constantly.

![image](https://user-images.githubusercontent.com/105431256/168069002-a7f6d8d3-c609-4105-90a1-197ce4e9f2d0.png)

I have searched for information and reviewed the php variables. In this issue it´s explained how to solve but not working for me.

https://github.com/Cacti/cacti/commit/38f3e89bc58c386830f7fd436573f75251a19bfc

My config file include/global_arrays.php

![image](https://user-images.githubusercontent.com/105431256/168068901-6cf3521b-c576-457d-910b-795207a1e6bb.png)

 No plugins installed yet

 - OS: [Ubuntu 22.04 LTS]
 - PHP: [8.1.2]
 - Browser [chrome, firefox]
 - Version [1.2.20]

Thanks in advance

**Comment by TheWitness** [comment]
This will be fixed in 1.2.21 to be released shortly (I think).  If you update to the 1.2.x branch (which is essentially 1.2.21 right now), the problem will go away.  We've been in lock down since the last two weeks.  So, likely no more changes before release.

**Comment by luistriunfo** [comment]
Okay! I will wait for update.

Thank you very much
