### ISSUE TITLE
Flowview 3.3 cause crash of cacti, gorwing process from 4 to over 400

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#77]
Using flowview 3.3 on cacti 1.2.21 I find out that every night arround midnight the system crash.

After having some doubt on the VM infrastructure, I find out that the cause of it was flowview.

The process flowview_process.php is growing from 4 to over 400, starting around 3pm (why ?) to around midnight over 400.
Then it crash ans start over at 4, again until 3pm, when it start to grow.

I have 1 collector, with 10 L3 router sending flowview information, each of one having something like 1000 IP, but I have no clue how many flow are going through.

Looking on the DB, the process are the following:
SELECT COUNT(*) FROM plugin_flowview_raw_2022157 WHERE end_time >= '2022-06-07 21:20:28'
.
.
.
SELECT COUNT(*) FROM plugin_flowview_raw_2022157 WHERE end_time >= '2022-06-07 15:52:20'

One query every 59seconds

Each of the flowview_raw_xxx contain over 100'000'000 records
I try to activated the debug changing the call on setup.php to 'flowview_process.php debug'

but nothing is logged on cacti.log

As suggested by TheWitness I try to setup a new index for end_time, it take 5 minute on each of my table to do so.
Don't know yet if it's help.

Is my flowview badly configured:
1 listener, 10 L3 device sending information on it.

So far no scheduler, but even on the flowview query I can't have a decent filter to work (other issue open on it)

I have no idea how to go further in the test, until I'm able to enable to log some debug information!

**Comment by TheWitness** [comment]
How much ram on that system?  How big are the raw tables.  You need like 3-4x the size of those tables for your innodb_buffer_pool_size.  Then, we may have to switch to hourly or semi-hourly partitions to work around the sheer size. .

**Comment by arno-st** [comment]
Hi,
My server has only 64G of RAM, and the buffer is 
innodb_buffer_pool_size = 15690M

**Comment by TheWitness** [comment]
I would have that beefed up if you plan on thes large tables.  I have a separated setup and it's a 1.5TB database server.  60+% for the innodb buffer pool.  We have a similar set of flows.  Less records, but very big records.

**Comment by TheWitness** [comment]
I would do this schema using MariaDB Column Store maybe at some point in the future or use MariaDB eXpand, but to do well, you need commercial support from MariaDB.

I will be evaluating eXpand this year and am already talking to them about it. I plan on using flowview as my guinny pig.

**Comment by arno-st** [comment]
I switch to Hourly table, but now I have an error:

10/06/2022  07:06:25 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[338]:process_fv5(),  /plugins/flowview/flow_collector.php[484]:db_execute(),  /lib/database.php[272]:db_execute_prepared())
10/06/2022 07:06:25 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.plugin_flowview_raw_2022160' doesn't exist
 
And if I look on my db, the table are called plugin_flowview_raw_202216000
with 2 more 0 and the end !!

**Comment by TheWitness** [comment]
If you log off and on again does it fix itself?

**Comment by TheWitness** [comment]
I made a slight change.  Grab the development branch.

**Comment by arno-st** [comment]
> If you log off and on again does it fix itself?

No the problem is nothing to do with a logon/logoff it's the way flowview try to reach the table.
Somehow on onep lace the table are created with two 0 but flowview_collector look with only one 0

here is another example:
13/06/2022  09:34:28 - CMDPHP SQL Backtrace:   (/plugins/flowview/flow_collector.php[338]:process_fv5(),  /plugins/flowview/flow_collector.php[484]:db_execute(),  /lib/database.php[272]:db_execute_prepared())
--
13/06/2022 09:34:28 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti.plugin_flowview_raw_2022163' doesn't exist

And the table name are:
plugin_flowview_raw_202216003

So again two 0 missing.

I'm gona look into flowview_collector, to try to change the code for now, I don't whant to have to re-create the table avery now and then.

And I will try you dev branch before that.

**Comment by arno-st** [comment]
So maybe I mess up a little bit during an upgrade, not sure.

I think when you chage the Database Partitioning Scheme from day, to hourly, it's not handle correctly, or I miss something (restart of the flowview collector. But no information on that.
So I erase all plugin_flowview_raw_ and restart flow_collector.php, so far it recreate the table correctly on a 'a needed basis'

But now I have an error in my log:
13/06/2022 15:32:32 - FLOWVIEW WARNING: Field length not set for name:packetDeltaCount, id: 2 has length 8

And that for every field that come from my Cisco device.

**Comment by arno-st** [comment]
The last error is on another incident, so I close this one
