### ISSUE TITLE
Warning in version 3.3 with packet in netflow V5 or V9, Field length not set for name ...

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#79]
Hello,
I have a lot of warning in my flowview 3.3:
29/06/2022 07:29:11 - FLOWVIEW WARNING: Field length not set for name:packetDeltaCount, id: 2 has length 8
--
29/06/2022 07:29:11 - FLOWVIEW WARNING: Field length not set for name:octetDeltaCount, id: 1 has length 8
29/06/2022 07:29:11 - FLOWVIEW WARNING: Field length not set for name:destinationTransportPort, id: 11 has length 2
29/06/2022 07:29:11 - FLOWVIEW WARNING: Field length not set for name:sourceTransportPort, id: 7 has length 2

And frankly I don't know how to resolve it, My flowview feed is mostly V5, but I have 3 device who send in V9 format.
So, I'm looking for a way either to remove this warning (it's filling my log) or to solve the issue.

Any input welcome.

**Comment by TheWitness** [comment]
Yea, this is a warning that can be ignored.  Going to bump it to HIGH as it's mainly for debugging.

**Comment by TheWitness** [comment]
Just updated it.

**Comment by arno-st** [comment]
Finally I tried to upgrade flowview, to see all you' resolved' status.
But still I have this error on my cacti log:
`
17/02/2023 10:36:07 - FLOWVIEW WARNING: Field length not set for name:packetDeltaCount, id: 2 has length 8
17/02/2023 10:36:07 - FLOWVIEW WARNING: Field length not set for name:octetDeltaCount, id: 1 has length 8
17/02/2023 10:36:07 - FLOWVIEW WARNING: Field length not set for name:destinationTransportPort, id: 11 has length 2
17/02/2023 10:36:07 - FLOWVIEW WARNING: Field length not set for name:sourceTransportPort, id: 7 has length 2
`

I'm using this command to upgrade my version, and I think the develop branch is the one by default.
git clone https://github.com/Cacti/plugin_flowview.git

**Comment by TheWitness** [comment]
Can you switch any of those V9 to V5 and see if the errors go away?  From my perspective, when I wrote the V9 and IPFIX versions, I did a quick read of the specification, and I may have assumed that the templates were static.  So, I may need to revisit that and re-initialize the templates every time a new template shows up in a specific stream to ensure that the collector picks up the changes in the template layouts, assuming that's the defect.

To do this I need time, and frankly, I'm so flush with things that I want to do and not enough time to pull them all off these days.  Getting the WeatherMap plugin into good shape took a lot of time.  So, been taking a break this week from Cacti development outside the corporate setting.
