### ISSUE TITLE
Error messages when generating a report with the flowview plugin

### ISSUE THREAD

**Issue by MRTA1** [Cacti/plugin_flowview#80]
Dear GitHub Forum,

I have installed and enabled the 'Flowview' plugin. I have created the 'Listener' and a 'Filter'. I receive an error message when I try to generate a report by choosing the filter function from the 'Flowview' tab. The following error messages are displayed:

022-11-03 12:50:23 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/flowview/flowview.php[65]:load_data_for_filter(), /plugins/flowview/functions.php[1350]:run_flow_query(), /plugins/flowview/functions.php[2452]:CactiErrorHandler())
2022-11-03 12:50:23 - ERROR PHP WARNING in Plugin 'flowview': Division by zero in file: /var/www/html/cacti/plugins/flowview/functions.php on line: 2452

Below is the Cacti configuration on my desktop computer:

- Ubuntu version: 20.04.5
- Flowview plugin version: 3.3
- Cacti version: 1.2.22
- PHP version: 7.4.3
- MariaDB version: 10.3.34

I have entered the IP address of a modem /router as a listener using port 2055. I have defined the 'Statistical Report' as 'Summary'. I have defined the protocol filters as 'TCP, UDP, ICMP, IGMP, GGP, IPENCAP, ST, CBT, EGP, IGP'. Also, please note that I have not made any configuration changes on the source router.

I would greatly appreciate your help in resolving the issue with the error messages. In addition, I would appreciate it if you can indicate how I can check whether any data has been stored in the MariaDB database from the router.

**Comment by MRTA1** [comment]
Dear GitHub Forum,

I would greatly appreciate any feedback on the error messages I reported when I try to generate a report.

**Comment by TheWitness** [comment]
I'll take a peak tonight.

**Comment by MRTA1** [comment]
Thank you.  I appreciate it.

**Comment by TheWitness** [comment]
Can you please update flowview to the develop branch.  The line numbers are not aligning, and it looks like this issue has already been handled.

**Comment by MRTA1** [comment]
Thank you for your assistance.  I un-installed the existing flowview plugin and re-installed the development branch.  I no longer receive the previous error messages when I try to generate a report.  

I do not see any data on the reports I am trying to generate; however, it appears that this is a separate issue.

**Comment by TheWitness** [comment]
Closing this now.  It'll be included in the next release.
