### ISSUE TITLE
/plugins/flowview/flowview_process.php[147]:set_config_option(), /lib/functions.php[422]:db_execute_prepared()

### ISSUE THREAD

**Issue by nishikozi** [Cacti/plugin_flowview#81]
I get an error every time the poller runs.
Please give me a hint to fix the error.

CMDPHP SQL Backtrace: (/plugins/flowview/flowview_process.php[147]:set_config_option(), /lib/functions.php[422]:db_execute_prepared())
CMDPHP ERROR: A DB Exec Failed!, Error: Column 'value' cannot be null
![image](https://user-images.githubusercontent.com/118161198/201611583-add3b1c6-7234-444e-8a51-dfff1db111f6.png)

OS version:  Red Hat Enterprise Linux 8.7
Flowview plugin version: 3.3
Cacti version: 1.2.22
PHP version: 7.2.24
MariaDB version: 10.3.35

**Comment by TheWitness** [comment]
Okay.  I'll look at this this morning.

**Comment by TheWitness** [comment]
Should be resolved no.  Do a fresh pull and let me know.

**Comment by nishikozi** [comment]
> Should be resolved no. Do a fresh pull and let me know.

I tried a fresh pull.
No errors so far.
Thank you very much!
