### ISSUE TITLE
Report Filter Listener Print All Rows Not Working

### ISSUE THREAD

**Issue by sdcxp** [Cacti/plugin_flowview#85]
When generate report only for specific source/listener return data for all flows, not only for specific listener.
using current build from Git  .
Also when generate report and chose unlimited number of lines return only 20 lines .

**Comment by TheWitness** [comment]
Sounds like a feature request.  Good one though.

**Comment by sdcxp** [comment]
hmm, because I see the option available in filters, I thought it is not working … not thinking it is a future work in progress 😊

**Comment by TheWitness** [comment]
There are so many things on the docket.  Loosing my mind.

**Comment by TheWitness** [comment]
There is no 'All' or rather 'N/A'.  So, it's a feature request.

![image](https://user-images.githubusercontent.com/1439914/224846320-7099f5bf-ca5f-4ea1-8eb2-f00b96f93d8b.png)

**Comment by TheWitness** [comment]
To be honest, there USED to be a reason for that limitation, which has long since gone.

**Comment by sdcxp** [comment]
Return all Lines it is in define filters function 
![image](https://user-images.githubusercontent.com/122022177/225013579-065402f1-d495-49c5-8275-d5c52f7c8d73.png)
and in  FlowView tab 
![image](https://user-images.githubusercontent.com/122022177/225013225-a1ba3be8-0727-43a4-8e96-01d87cfe6ae3.png)
Dropdown with Listern filter it is in Filters Function
![image](https://user-images.githubusercontent.com/122022177/225014040-625638ea-d076-41d7-9ac8-5bbba3d6cc97.png)

**Comment by TheWitness** [comment]
This is fixed.
