### ISSUE TITLE
Create new Custom Flow Viewer Report

### ISSUE THREAD

**Issue by tgreaser** [Cacti/plugin_flowview#88]
Is it possible to create the Flow Viewer to include a report showing   dstport,dstip,srcip,srcport 

**Describe the solution you'd like**
Is it possible to create the Flow Viewer to include a report showing   dstport,dstip,srcip,srcport 

**Describe alternatives you've considered**
I have tired to create custom filter in conjunction with the Flow Viewer report and still the same results.

In some other tools I have used I could create a default query / report showing
dstport,dstip,srcip,srcport as well as the  flow, packet, byte counts.
This sould help to see those 4 or normal 5 turples if possible.

**Comment by TheWitness** [comment]
I'm pretty sure it's a yes.  It's all about time.

**Comment by TheWitness** [comment]
This is resolved now.
