### ISSUE TITLE
Folwview not working in cact 1.2.25

### ISSUE THREAD

**Issue by Evil8864** [Cacti/plugin_flowview#89]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [e.g. 1.2]
 - Source: [e.g. cacti.net, package, github]
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Evil8864** [comment]
When I send netflow traffic from router database crash automatically

**Comment by Evil8864** [comment]
Please share tha process of installation on Debian 11

**Comment by cigamit** [comment]
This is not a support forum, for support, please goto https://forums.cacti.net
