### ISSUE TITLE
Support Pie Charts Instead of Bar

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_flowview#9]
Hi there,

Is it too much to ask for pie chart option?

Can we also do something about the red square you can see in the screenshot attached? it's all overlapped.

![firefox_2017-07-11_09-38-04](https://user-images.githubusercontent.com/13456559/28041317-0e18979e-661d-11e7-9f01-c1efdf00cb55.png)

Thanks

**Comment by cigamit** [comment]
Additionally, I would like to drop flash charts as that is what is causing you the issues with your browser.  Replace it with either C3.js or one of the other graph frameworks built into Cacti.  If you would take that one on, we would be very happy to receive a pull request from you.

**Comment by cigamit** [comment]
I made the bar charts a little bigger.  I have a number of plans for this plugin.  Just need to get it onto the schedule.  Going to be a while.  Maybe closer to Christmas holiday.

**Comment by cigamit** [comment]
Making progress.  Glad you are testing.  Going to keep this open for the moment.

**Comment by TheWitness** [comment]
@jpobeda, you should be okay to test now.  Just about everything works now.  If you have a lot of data in files, it'll take a while to load into the database.

**Comment by TheWitness** [comment]
There is currently not a pie option though.

**Comment by xmacan** [comment]
I will look at it soon

**Comment by TheWitness** [comment]
@xmacan, any progress?

**Comment by xmacan** [comment]
I will try it today or it has to wait more than week. I will have holiday next week.

**Comment by TheWitness** [comment]
Make the 4 check boxes a multi-select and add some pie options.  Allow the Summary Report to be pie and bar too.  We can wait till after release too

**Comment by TheWitness** [comment]
![image](https://github.com/Cacti/plugin_flowview/assets/1439914/459a5d22-06fd-435b-8fd5-bb376d9f802e)
