### ISSUE TITLE
HUAWEI NetEngine 8000 M1A flowview

### ISSUE THREAD

**Issue by Evil8864** [Cacti/plugin_flowview#90]
Huawei netstream data not received from huawei router.

ip netstream timeout active 1
ip netstream timeout inactive 15
ip netstream export version 9
ip netstream export template timeout-rate 1
ip netstream export source * * * *
ip netstream export host * * * *

Under all interfaces:

ip netstream inbound
ip netstream inbound

Please help

**Comment by TheWitness** [comment]
What's the question?

**Comment by TheWitness** [comment]
@Evil8864, can you please test again with the latest develop?  I'm pretty sure this is resolved now.

**Comment by TheWitness** [comment]
Closing with no feedback.
