### ISSUE TITLE
Add the possibilites for Flowview to use a different DB than the Cacti one

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_flowview#91]
Due to the charge on my DB, I need to use an other DB than Cacti.
So far only the flow_collector.php can access another DB, than Cacti, but it's the only part.

I think it can be a good idea to have flowview to be able to use a separate DB than Cacti.
Like it's offered on the plugin syslog.

**Comment by TheWitness** [comment]
Totally agree.  Can you do a pull request?

**Comment by arno-st** [comment]
I'm on it.
I will take the same approach that was done on syslog

I already fork the dev branch.

**Comment by TheWitness** [comment]
Awesome.  I was going to recommend it's DB library, though the base library works these days too.

**Comment by arno-st** [comment]
Well the change are going well.
But I'm facing an issue and I don't know how to handle it.

On flowview_schedules.php, on the $schedule_edit array, the field 'query_id' has a method of 'drop_sql' with an sql query.

All of this is used by the function draw_edit_form (from lib/html_form.php) to make a call to the DB, but it's the Cacti DB, and I have no way to change that in a simple manner!

Any clue on which way I should go to solve that issue ?

**Comment by TheWitness** [comment]
Just use `drop_array`.  Pass to the form object of rows with each element having two columns 'id', 'name' and we don't need `drop_sql`.

**Comment by arno-st** [comment]
Simple thanks, and it works (of curse)!

So far it's looking well, for all my test the data are stored in another DB, and I have no error related to that.
But it's only on a brand new install. Now I will have to work on the upgrade process. I have an idea on how to do it.

**Comment by arno-st** [comment]
Can you check my Pull resquest, this one dosen't include the upgrade part, and still hase some cacti_log,
So a quick check and disregard it after that.

**Comment by TheWitness** [comment]
You may want to save your changes, and merge the upgrade Cacti develop into your local repo.  Then, you can replace your modified files.

![image](https://github.com/Cacti/plugin_flowview/assets/1439914/24d2461d-7537-4d66-b55e-4a9b7de8f785)

**Comment by TheWitness** [comment]
This is merged now.  Thanks for your contribution @arno-st !

**Comment by arno-st** [comment]
Hi,
Well you do it a little to early!
The use of an external database was almost finish (just a few detail), but I't missing the upgrade process.
When you change your config from Cacti DB to External DB.
It's almost finish.

**Comment by TheWitness** [comment]
Okay, next pull request against the `develop` branch ;)
